<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Luku 6 Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle | Tilastotieteen ja data-analytiikan jatkokurssi</title>
  <meta name="description" content="Luku 6 Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Luku 6 Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Luku 6 Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle | Tilastotieteen ja data-analytiikan jatkokurssi" />
  
  
  

<meta name="author" content="Jaakko Pere" />


<meta name="date" content="2026-03-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="epäparametrisia-tilastollisia-testejä.html"/>
<link rel="next" href="estimoinnista.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://mycourses.aalto.fi/course/view.php?id=48142" target="blank">ISM-C1002</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alustava kurssiohjelma</a></li>
<li class="chapter" data-level="1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html"><i class="fa fa-check"></i><b>1</b> R ohjelmointikielestä</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:inst"><i class="fa fa-check"></i><b>1.1</b> Ohjelmointikieli ja -ympäristö: asennus ja käyttö</a></li>
<li class="chapter" data-level="1.2" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:programming"><i class="fa fa-check"></i><b>1.2</b> Ohjelmoinnin opettelu</a></li>
<li class="chapter" data-level="1.3" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:packages"><i class="fa fa-check"></i><b>1.3</b> R-paketit</a></li>
<li class="chapter" data-level="1.4" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:demo"><i class="fa fa-check"></i><b>1.4</b> Data-analyysin askeleet</a></li>
<li class="chapter" data-level="1.5" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:markdown"><i class="fa fa-check"></i><b>1.5</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html"><i class="fa fa-check"></i><b>2</b> Moniulotteiset jakaumat</a>
<ul>
<li class="chapter" data-level="2.1" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:dep"><i class="fa fa-check"></i><b>2.1</b> Stokastinen riippumattomuus</a></li>
<li class="chapter" data-level="2.2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:rvec"><i class="fa fa-check"></i><b>2.2</b> Perusteet</a></li>
<li class="chapter" data-level="2.3" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:normal"><i class="fa fa-check"></i><b>2.3</b> Moniulotteinen normaalijakauma</a></li>
<li class="chapter" data-level="2.4" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:cond"><i class="fa fa-check"></i><b>2.4</b> Yhteisjakaumaan koodattu informaatio</a></li>
<li class="chapter" data-level="2.5" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:statistic"><i class="fa fa-check"></i><b>2.5</b> Tunnusluvuista</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html"><i class="fa fa-check"></i><b>3</b> Moniulotteinen lineaarinen regressio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:regdef"><i class="fa fa-check"></i><b>3.1</b> Määritelmä ja oletukset</a></li>
<li class="chapter" data-level="3.2" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:fitting"><i class="fa fa-check"></i><b>3.2</b> Mallin sovittaminen ja tulkinta</a></li>
<li class="chapter" data-level="3.3" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:determination"><i class="fa fa-check"></i><b>3.3</b> Sovitteen hyvyys ja ennustaminen</a></li>
<li class="chapter" data-level="3.4" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:diagnostic"><i class="fa fa-check"></i><b>3.4</b> Mallidiagnostiikka</a></li>
<li class="chapter" data-level="3.5" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:regtesting"><i class="fa fa-check"></i><b>3.5</b> Malliin liittyvät epävarmuudet</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ryhmien-odotusarvojen-vertailu.html"><a href="ryhmien-odotusarvojen-vertailu.html"><i class="fa fa-check"></i><b>4</b> Ryhmien odotusarvojen vertailu</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ryhmien-odotusarvojen-vertailu.html"><a href="ryhmien-odotusarvojen-vertailu.html#sec:dummy"><i class="fa fa-check"></i><b>4.1</b> Luokkamuuttujat lineaarisessa regressiossa</a></li>
<li class="chapter" data-level="4.2" data-path="ryhmien-odotusarvojen-vertailu.html"><a href="ryhmien-odotusarvojen-vertailu.html#sec:twosample"><i class="fa fa-check"></i><b>4.2</b> Kahden otoksen t-testi</a></li>
<li class="chapter" data-level="4.3" data-path="ryhmien-odotusarvojen-vertailu.html"><a href="ryhmien-odotusarvojen-vertailu.html#sec:anova"><i class="fa fa-check"></i><b>4.3</b> Yksisuuntainen varianssianalyysi</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="epäparametrisia-tilastollisia-testejä.html"><a href="epäparametrisia-tilastollisia-testejä.html"><i class="fa fa-check"></i><b>5</b> Epäparametrisia tilastollisia testejä</a>
<ul>
<li class="chapter" data-level="5.1" data-path="epäparametrisia-tilastollisia-testejä.html"><a href="epäparametrisia-tilastollisia-testejä.html#sec:signtest"><i class="fa fa-check"></i><b>5.1</b> Merkkitesti</a></li>
<li class="chapter" data-level="5.2" data-path="epäparametrisia-tilastollisia-testejä.html"><a href="epäparametrisia-tilastollisia-testejä.html#sec:signedranktest"><i class="fa fa-check"></i><b>5.2</b> Merkkisijatesti</a></li>
<li class="chapter" data-level="5.3" data-path="epäparametrisia-tilastollisia-testejä.html"><a href="epäparametrisia-tilastollisia-testejä.html#sec:ranksum"><i class="fa fa-check"></i><b>5.3</b> Sijasummatesti</a></li>
<li class="chapter" data-level="5.4" data-path="epäparametrisia-tilastollisia-testejä.html"><a href="epäparametrisia-tilastollisia-testejä.html#sec:nonparammultiplesample"><i class="fa fa-check"></i><b>5.4</b> Kruskal–Wallis testi</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html"><i class="fa fa-check"></i><b>6</b> Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle</a>
<ul>
<li class="chapter" data-level="6.1" data-path="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:permutation"><i class="fa fa-check"></i><b>6.1</b> Permutaatiotesti</a></li>
<li class="chapter" data-level="6.2" data-path="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:bootstrap"><i class="fa fa-check"></i><b>6.2</b> Uusiomenetelmä</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="estimoinnista.html"><a href="estimoinnista.html"><i class="fa fa-check"></i><b>7</b> Estimoinnista</a>
<ul>
<li class="chapter" data-level="7.1" data-path="estimoinnista.html"><a href="estimoinnista.html#sec:mle"><i class="fa fa-check"></i><b>7.1</b> Suurimman uskottavuuden menetelmä</a></li>
<li class="chapter" data-level="7.2" data-path="estimoinnista.html"><a href="estimoinnista.html#sec:moment"><i class="fa fa-check"></i><b>7.2</b> Momenttimenetelmä</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="liitteet.html"><a href="liitteet.html"><i class="fa fa-check"></i><b>8</b> Liitteet</a>
<ul>
<li class="chapter" data-level="8.1" data-path="liitteet.html"><a href="liitteet.html#sec:vector"><i class="fa fa-check"></i><b>8.1</b> Vektoreista</a></li>
<li class="chapter" data-level="8.2" data-path="liitteet.html"><a href="liitteet.html#sec:matrix"><i class="fa fa-check"></i><b>8.2</b> Matriiseista</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="lähteet.html"><a href="lähteet.html"><i class="fa fa-check"></i>Lähteet</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Julkaistu bookdownin avulla</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tilastotieteen ja data-analytiikan jatkokurssi</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Luku 6</span> Epäparametrisia tilastollisia menetelmiä lineaariselle regressiolle<a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#ep%C3%A4parametrisia-tilastollisia-menetelmi%C3%A4-lineaariselle-regressiolle" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Luvussa <a href="moniulotteinen-lineaarinen-regressio.html#sec:regtesting">3.5</a> käsittelimme tilastollisia testejä liittyen lineaariseen regressiomalliin
<span class="math display" id="eq:linearnonparam">\[\begin{equation}
  \tag{6.1}
  y_i = \beta_0  + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_d x_{id} + \varepsilon_i, \quad i\in\{1, \ldots, n\}.
\end{equation}\]</span>
Käsitellyt testit olivat parametrisia, koska testeissä oletimme satunaisvirheiden noudattavan normaalijakaumaa (katso määritelmä <a href="moniulotteinen-lineaarinen-regressio.html#def:whitenoise">3.1</a> valkoiselle kohinalle).</p>
<p>Kuitenkin usein on kohtuutonta olettaa, että satunnaistermit <span class="math inline">\(\varepsilon_i\)</span> noudattavat jotain tiettyä parametrista jakaumaa kuten normaalijakaumaa. Tämän vuoksi tässä luvussa esittelemme epäparametrisia menetelmiä lineaarisen regression kontekstissa. Luvussa <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:permutation">6.1</a> annamme epäparametriset vastineet luvun <a href="moniulotteinen-lineaarinen-regressio.html#sec:regtesting">3.5</a> tilastollisille testeille. Luvussa <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:bootstrap">6.2</a> esittelemme epäparametrisen menetelmän luottamusvälien muodostamiseen parametreille <span class="math inline">\(\beta_j\)</span>.</p>
<p><strong>Kaikissa tämän luvun menetelmissä oletamme, että virhetermit ovat määritelmän <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#def:whitenoiserelax">6.1</a> mukaista valkoista kohinaa. Ero määritelmien <a href="moniulotteinen-lineaarinen-regressio.html#def:whitenoise">3.1</a> ja <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#def:whitenoiserelax">6.1</a> välillä on, että nyt emme oleta virhetermeille mitään tiettyä jakaumaa.</strong></p>
<div class="definition">
<p><span id="def:whitenoiserelax" class="definition"><strong>Määritelmä 6.1  (Valkoinen kohina, joustavampi määritelmä) </strong></span>Mallin <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#eq:linearnonparam">(6.1)</a> virheet <span class="math inline">\(\varepsilon_i\)</span> ovat satunnaismuuttujia, joille pätee seuraavat oletukset.</p>
<ol style="list-style-type: decimal">
<li><p>Satunnaisvirheet <span class="math inline">\(\varepsilon_i\)</span> ovat riippumattomia ja samoin jakautuneita.</p></li>
<li><p>Kaikkien satunnaisvirheiden <span class="math inline">\(\varepsilon_i\)</span> odotusarvo on nolla ja varianssi ei riipu indeksistä <span class="math inline">\(i\)</span> eli
<span class="math display">\[\begin{equation*}
  \mathbb{E}(\varepsilon_i) = 0 \quad\text{ja}\quad \mathrm{Var}(\varepsilon_i) = \sigma^2 &gt; 0 \quad\text{kaikille}\quad i\in\{1,\ldots, n\}.
\end{equation*}\]</span></p></li>
</ol>
</div>
<div id="sec:permutation" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Permutaatiotesti<a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:permutation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ensin esittelemme epäparametrisen vastineen lineaarisen mallin merkitsevyyden testaamiseen (parametrinen testi olisi F-testi). Tämän jälkeen esittelemme epäparametrisen vastineen yhden kertoimen <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j\in\{1, \ldots, d\}\)</span>, merkitsevyyden testaamiseen (parametrinen testi olisi t-testi).</p>
<p>Luvun molempien testien ideat ovat hyvin samankaltaisia – testeissä dataa “sekoitetaan” eli permutoidaan jollain tavalla. Tämän vuoksi näitä tilastollisia testejä kutsutaan permutaatiotesteiksi.</p>
<div id="mallin-merkitsevyys" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Mallin merkitsevyys<a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#mallin-merkitsevyys" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>F-testin testisuure kaavassa <a href="moniulotteinen-lineaarinen-regressio.html#eq:fstat">(3.11)</a> lasketaan selitysasteen <span class="math inline">\(R^2\)</span> (joka aina välillä <span class="math inline">\([0,1]\)</span>) avulla. Muista, että <span class="math inline">\(R^2\)</span> kuvaa sitä, kuinka suuren osan selitettävän muuttujan <span class="math inline">\(y\)</span> vaihtelusta sovitettu malli selittää. Jos <span class="math inline">\(R^2\approx 1,\)</span> niin malli selittää suuren osan selitettävän muuttujan vaihtelusta. Jos <span class="math inline">\(R^2\approx 0\)</span>, niin satunnaisvirhe selittää suurimman osan selitettävän muuttujan vaihtelusta.</p>
<p>Myös epäparametrinen testi mallin merkitsevyydelle voidaan rakentaa selitysasteen avulla. Ideana on tutkia, onko <span class="math inline">\(R^2\)</span> arvo tietynlainen (esimerkiksi <span class="math inline">\(0.2\)</span>, <span class="math inline">\(0.001\)</span> tai <span class="math inline">\(0.5\)</span>) vain sattumalta vai kuvaako <span class="math inline">\(R^2\)</span> arvo sitä, että malli on oleellinen selitettävän ilmiön kannalta. Voisi siis ajatella, että jos “satunnaisella” datalla saamme samaa suuruusluokkaa olevan <span class="math inline">\(R^2\)</span> arvon kuin alkuperäisellä datalla, niin malli ei ole merkitsevä. Permutaatiotesti (eng: <em>permutation test</em>) perustuu juuri tähän ideaan. Permutaatiotestissä testaamme seuraavaa nollahypoteesia <span class="math inline">\(H_0\)</span> vaihtoehtoista hypoteesia <span class="math inline">\(H_1\)</span> vastaan
<span class="math display">\[\begin{equation*}
  \begin{split}
    &amp;H_0: \beta_1  = \beta_2 = \cdots = \beta_d = 0, \\
    &amp;H_1: \beta_j \neq 0 \quad\text{jollekin}\quad j\in\{1, \ldots, d\}.
  \end{split}
\end{equation*}\]</span>
Nämä ovat siis täysin samat hypoteesit kuin F-testissä. Permutaatiotesti mallin merkitsevyydelle merkitsevyystasolla <span class="math inline">\(\alpha\)</span> (esimerkiksi <span class="math inline">\(\alpha = 0.05\)</span>) suoritetaan seuraavasti.</p>
<ol style="list-style-type: decimal">
<li><p>Olkoon
<span class="math display">\[\begin{equation*}
  \left\{\underbrace{(y_1, x_{11}, x_{12}, \ldots, x_{1d})}_{\text{$(d+1)$-ulotteinen havainto nro $1$}}, \ldots, \underbrace{(y_n, x_{n1}, x_{n2}, \ldots, x_{nd})}_{\text{$(d+1)$-ulotteinen havainto nro $n$}}\right\}
\end{equation*}\]</span>
alkuperäinen otos, jonka otoskoko on <span class="math inline">\(n\)</span>. Kirjoitetaan havainto <span class="math inline">\(i\)</span> muodossa <span class="math inline">\((y_i, x_{i1}, x_{i2}, \ldots, x_{id}) = (y_i, \boldsymbol x_i)\)</span>, jossa <span class="math inline">\(\boldsymbol x_i\in\mathbb{R}^d\)</span>. Laske selitysaste <span class="math inline">\(R^2\)</span> alkuperäisestä otoksesta <span class="math inline">\(\left\{(y_1, \boldsymbol x_1), \ldots, (y_n, \boldsymbol x_n)\right\}\)</span>.</p></li>
<li><p>Olkoon <span class="math inline">\(i,\ell\in\{1, \ldots, n\}\)</span>. Muodosta uusi <span class="math inline">\(n\)</span> kokoinen otos, joka koostuu uusista pareista <span class="math inline">\((y_i, \boldsymbol x_{\ell})\)</span>, joissa mahdollisesti <span class="math inline">\(\ell\neq i\)</span>. Muodosta parit niin, että jokainen alkuperäisen otoksen <span class="math inline">\(y_i\)</span> ja <span class="math inline">\(x_\ell\)</span> käytetään tasan kerran.</p></li>
<li><p>Askeleen 2 mukaisia permutoituja otoksia on mahdollista muodostaa <span class="math inline">\(n!\)</span> kappaletta. Muodosta siis kaikki mahdolliset permutoidut otokset.</p></li>
<li><p>Laske selitysaste <span class="math inline">\(R_k^2\)</span> jokaiselle <span class="math inline">\(k = 1, \ldots, n!\)</span> permutoidulle otokselle.</p></li>
<li><p>Järjestä arvot <span class="math inline">\(R_1^2, \ldots, R_{n!}\)</span> suuruusjärjestykseen. Laske <span class="math inline">\(\left[(1 - \alpha)\times m\right]\)</span> järjestetty selitysaste. Tässä notaatio <span class="math inline">\([\cdot]\)</span> tarkoittaa pyöristämistä lähimpään kokonaislukuun. Tarkoitus on siis laskea selitysasteita <span class="math inline">\(\left\{R_1^2, \ldots, R_{n!}^2\right\}\)</span> vastaava <span class="math inline">\((1 - \alpha)\)</span>-otoskvantiili. Jos alkuperäisestä otoksesta laskettu <span class="math inline">\(R^2\)</span> on suurempi kuin laskettu otoskvantiili, niin nollahypoteesi <span class="math inline">\(H_0\)</span> hylätään.</p></li>
</ol>
<div class="proposition">
<p><span id="prp:permutation" class="proposition"><strong>Huomautus 6.1  </strong></span>Yllä kuvatussa permutaatiotestin algoritmissa muodostamme <span class="math inline">\(n!\)</span> otosta askeleessa 2. Tämä voi olla kuitenkin laskennallisesti liian vaativaa jopa suhteellisen pienille otoksille. Esimerkiksi jos otoskoko on <span class="math inline">\(n = 10\)</span>, niin meidän täytyisi muodostaa <span class="math inline">\(n! = 10 \cdot 9 \cdot \ldots \cdot 2\cdot 1 \approx 3.6 \cdot 10^6\)</span> permutoitua otosta. Usein tapana on siis suorittaa permutaatiotesti satunnaisesti valituilla otoksilla, kun otoksia valitaan esimerkiksi <span class="math inline">\(m = 1000\)</span> kappaletta. Tällöin permutaatiotestin tuloksiin liittyy pientä satunnaisuutta riippuen siitä, mitkä permutoidut otokset valitaan. Pidä tämä mielessä kun pääset tutkimaan esimerkkiin <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#exm:perm">6.2</a> liittyviä kuvia <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:twoperm">6.1</a> ja <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:oneperm">6.2</a>).</p>
</div>
<p>Alla sovellamme permutaatiotestiä mallin merkitsevyydelle käytännössä.</p>
<div class="example">
<p><span id="exm:unlabeled-div-42" class="example"><strong>Esimerkki 6.1  (Permutaatiotesti ja mallin merkitsevyys) </strong></span>Käytämme samaa dataa kuin esimerkissä <a href="moniulotteinen-lineaarinen-regressio.html#exm:fitreg">3.3</a>. Eli meillä on kuvitteellinen <span class="math inline">\(n = 10\)</span> kokoinen havaintoaineisto. Havainnot ovat toteumia satunnaisvektorista <span class="math inline">\((Y, X_1, X_2)\)</span>, jossa</p>
<ul>
<li><p><span class="math inline">\(Y = \text{voitto kuukaudessa tuhansina euroina}\)</span> (<code>profit</code>),</p></li>
<li><p><span class="math inline">\(X_1 = \text{mainosbudjetti kuukaudessa tuhansina euroina}\)</span> (<code>advertisement</code>) ja</p></li>
<li><p><span class="math inline">\(X_2 = \text{tuotteen hinta tuhansina euroina}\)</span> (<code>price</code>).</p></li>
</ul>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb220-1" tabindex="-1"></a>sale</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 -15.2          2.88  4.78 
##  2   4.97         7.88  2.27 
##  3  -8.51         4.09  3.39 
##  4   2.64         8.83  2.86 
##  5  13.8          9.40  0.515
##  6 -16.2          0.456 4.50 
##  7   5.91         5.28  1.23 
##  8   8.85         8.92  0.210
##  9   4.98         5.51  1.64 
## 10 -18.5          4.57  4.77</code></pre>
<p>Tavoitteenamme on testata lineaarisen regressiomallin
<span class="math display">\[\begin{equation*}
  \texttt{profit}_i = \beta_0 + \beta_1 \texttt{advertisement}_i + \beta_2 \texttt{price}_i + \varepsilon_i
\end{equation*}\]</span>
merkitsevyyttä permutaatiotestillä. Asetamme merkitsevyystasoksi <span class="math inline">\(\alpha = 0.05\)</span>. Ennen kuin kirjoitamme permutaatiotestin algoritmin kokonaisuudessaan, kuvailemme tarkemmin muutamaa tärkeää askelta. Alkuperäisestä otoksesta laskettu selitysaste <span class="math inline">\(R^2\)</span> saadaan napattua funktion <code>summary()</code> tuottamasta muuttujasta.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb222-1" tabindex="-1"></a><span class="co"># Fit model and compute summary</span></span>
<span id="cb222-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb222-2" tabindex="-1"></a>sale_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> sale))</span>
<span id="cb222-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb222-3" tabindex="-1"></a></span>
<span id="cb222-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb222-4" tabindex="-1"></a><span class="co"># Inspect how to pick R^2</span></span>
<span id="cb222-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb222-5" tabindex="-1"></a><span class="fu">names</span>(sale_lm_summary)</span></code></pre></div>
<pre><code>##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;     &quot;coefficients&quot; 
##  [5] &quot;aliased&quot;       &quot;sigma&quot;         &quot;df&quot;            &quot;r.squared&quot;    
##  [9] &quot;adj.r.squared&quot; &quot;fstatistic&quot;    &quot;cov.unscaled&quot;</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb224-1" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> sale_lm_summary<span class="sc">$</span>r.squared</span>
<span id="cb224-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb224-2" tabindex="-1"></a>rsquared</span></code></pre></div>
<pre><code>## [1] 0.94611</code></pre>
<p>Seuraavaksi näytämme, miten yksi permutoitu otos muodostetaan. Permutoidun otoksen voi muodostaa valitsemalla selittävektoreiden arvoja alkuperäisestä taulukosta käyttämällä funktiota <code>sample()</code>. On erittäin tärkeää, että funktiossa <code>sample()</code> asetat <code>replace = FALSE</code>. Tällöin on mahdollista valita sama arvo <span class="math inline">\(\boldsymbol x_i\)</span> vain kerran.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb226-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-2" tabindex="-1"></a></span>
<span id="cb226-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-3" tabindex="-1"></a><span class="co"># Permutate observations of the explanatory variables</span></span>
<span id="cb226-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-4" tabindex="-1"></a>perm_sample_x <span class="ot">&lt;-</span> sale[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">FALSE</span>), <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb226-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-5" tabindex="-1"></a></span>
<span id="cb226-6"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-6" tabindex="-1"></a><span class="co"># Combine original y and permutated x</span></span>
<span id="cb226-7"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-7" tabindex="-1"></a>perm_sample <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_cols</span>(sale[, <span class="dv">1</span>], perm_sample_x)</span>
<span id="cb226-8"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb226-8" tabindex="-1"></a>perm_sample</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 -15.2          4.09  3.39 
##  2   4.97         4.57  4.77 
##  3  -8.51         7.88  2.27 
##  4   2.64         8.92  0.210
##  5  13.8          0.456 4.50 
##  6 -16.2          5.51  1.64 
##  7   5.91         2.88  4.78 
##  8   8.85         5.28  1.23 
##  9   4.98         9.40  0.515
## 10 -18.5          8.83  2.86</code></pre>
<p>Taulukoissa <code>sale</code> ja <code>perm_sample</code> selitettävää muuttujaa vastaava sarake (eli <code>profit</code>) on sama. Kuitenkin taulukossa <code>perm_sample</code> vektorit <span class="math inline">\((\texttt{advertisement}_i, \texttt{price}_i)\)</span> ovat vaihtaneet paikkoja. Esimerkiksi taulukossa <code>sale</code>,
<span class="math display">\[\begin{equation*}
(2.88, 4.78) = (\texttt{advertisement}_1, \texttt{price}_1)
\end{equation*}\]</span>
mutta taulukossa <code>perm_sample</code>
<span class="math display">\[\begin{equation*}
  (2.88, 4.78) = (\texttt{advertisement}_7, \texttt{price}_7).
\end{equation*}\]</span>
Permutoidusta otoksesta saadaan laskettua selitysaste <span class="math inline">\(R_k^2\)</span> samaan tyyliin kuin alkuperäisestä otoksesta.</p>
<p>Nyt olemme valmiita kirjoittamaan permutaatiotestin algoritmin askeleet 1–4. Selkeyden vuoksi toteutamme algoritmin <code>for</code> silmukan avulla.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-1" tabindex="-1"></a><span class="co"># Number of permutation samples</span></span>
<span id="cb228-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb228-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-3" tabindex="-1"></a></span>
<span id="cb228-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-4" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb228-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-5" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb228-6"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-6" tabindex="-1"></a></span>
<span id="cb228-7"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-7" tabindex="-1"></a><span class="co"># Create a vector for storing R^2</span></span>
<span id="cb228-8"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-8" tabindex="-1"></a>rsq_perm <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, m)</span>
<span id="cb228-9"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-9" tabindex="-1"></a></span>
<span id="cb228-10"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-10" tabindex="-1"></a><span class="co"># Compute R^2 from the original sample</span></span>
<span id="cb228-11"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-11" tabindex="-1"></a>sale_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> sale))</span>
<span id="cb228-12"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-12" tabindex="-1"></a>rsq_original <span class="ot">&lt;-</span> sale_lm_summary<span class="sc">$</span>r.squared</span>
<span id="cb228-13"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-13" tabindex="-1"></a></span>
<span id="cb228-14"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-14" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>m) {</span>
<span id="cb228-15"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-15" tabindex="-1"></a>  <span class="co"># Construct the ith permuted sample</span></span>
<span id="cb228-16"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-16" tabindex="-1"></a>  perm_sample_x <span class="ot">&lt;-</span> sale[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">FALSE</span>), <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb228-17"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-17" tabindex="-1"></a></span>
<span id="cb228-18"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-18" tabindex="-1"></a>  <span class="co"># Combine original y and permuted x</span></span>
<span id="cb228-19"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-19" tabindex="-1"></a>  perm_sample <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_cols</span>(sale[, <span class="dv">1</span>], perm_sample_x)</span>
<span id="cb228-20"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-20" tabindex="-1"></a>  </span>
<span id="cb228-21"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-21" tabindex="-1"></a>  <span class="co"># Compute R^2 from the permuted sample</span></span>
<span id="cb228-22"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-22" tabindex="-1"></a>  perm_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price,</span>
<span id="cb228-23"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-23" tabindex="-1"></a>                                <span class="at">data =</span> perm_sample))</span>
<span id="cb228-24"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-24" tabindex="-1"></a>  rsq_perm[i] <span class="ot">&lt;-</span> perm_lm_summary<span class="sc">$</span>r.squared</span>
<span id="cb228-25"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb228-25" tabindex="-1"></a>}</span></code></pre></div>
<p>Vektori <code>rsq_perm</code> sisältää nyt permutoituja otoksia vastaavat selitysasteet <span class="math inline">\(R_1^2, \ldots, R_m^2\)</span>.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb229-1" tabindex="-1"></a><span class="fu">head</span>(rsq_perm)</span></code></pre></div>
<pre><code>## [1] 0.5041981 0.3918123 0.2948301 0.1517311 0.1532220 0.1051823</code></pre>
<p>Jäljellä on vielä algoritmin askel 5. Haluamme siis laskea <span class="math inline">\((1-\alpha)\)</span>-otoskvantiilin selitysasteista <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span>, kun <span class="math inline">\(\alpha = 0.05\)</span>. Tämän voi helposti suorittaa funktiolla <code>quantile()</code>.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb231-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb231-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb231-2" tabindex="-1"></a>rsq_perm_quantile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(rsq_perm, <span class="at">probs =</span> <span class="dv">1</span> <span class="sc">-</span> alpha)</span>
<span id="cb231-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb231-3" tabindex="-1"></a>rsq_perm_quantile</span></code></pre></div>
<pre><code>##       95% 
## 0.6148804</code></pre>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb233-1" tabindex="-1"></a>rsq_original <span class="sc">&gt;</span> rsq_perm_quantile</span></code></pre></div>
<pre><code>##  95% 
## TRUE</code></pre>
<p>Alkuperäisestä otoksesta laskettu selitysaste on suurempi kuin yllä oleva <span class="math inline">\(0.95\)</span>-otoskvantiili, joten permutaatiotestin nollahypoteesi hylätään. Halutessasi voit myös laskea permutaatiotestin p-arvon vertaamalla kuinka suuri osuus selitysasteista <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span> on suurempaa kuin alkuperäisestä otoksesta laskettu selitysaste.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb235-1" tabindex="-1"></a><span class="fu">mean</span>(rsq_original <span class="sc">&lt;</span> rsq_perm)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Tässä tapauksessa p-arvo on käytännössä nolla.</p>
</div>
</div>
<div id="parametrien-merkitsevyys" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Parametrien merkitsevyys<a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#parametrien-merkitsevyys" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nyt haluamme testata yhden kertoimen merkitsevyyttä <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j\in\{1, \ldots, d\}\)</span>, samaan tyyliin kuin koko mallin merkitsevyyttä edellä. Esittelemme siis toisenlaisen permutaatiotestin, jolla testataan seuraavaa nollahypoteesia <span class="math inline">\(H_0\)</span> vaihtoehtoista hypoteesia <span class="math inline">\(H_1\)</span> vastaan
<span class="math display">\[\begin{equation*}
  \begin{split}
    &amp;H_0: \beta_j = 0, \\
    &amp;H_1: \beta_j \neq 0.
  \end{split}
\end{equation*}\]</span>
Nyt emme permutoi vektoreita <span class="math inline">\(\boldsymbol x_i = (x_{i1}, x_{i2}, \ldots, x_{id})\)</span> vaan ainoastaan parametria <span class="math inline">\(\beta_j\)</span> vastaavaa selittäjää. Tarkemmin ottaen permutaatiotesti parametrille <span class="math inline">\(\beta_j\)</span> merkitsevyystasolla <span class="math inline">\(\alpha\)</span> (esimerkiksi <span class="math inline">\(\alpha = 0.05\)</span>) suoritetaan seuraavasti.</p>
<ol style="list-style-type: decimal">
<li><p>Olkoon
<span class="math display">\[\begin{equation*}
  \left\{\underbrace{(y_1, x_{11}, x_{12}, \ldots, x_{1d})}_{\text{$(d+1)$-ulotteinen havainto nro $1$}}, \ldots, \underbrace{(y_n, x_{n1}, x_{n2}, \ldots, x_{nd})}_{\text{$(d+1)$-ulotteinen havainto nro $n$}}\right\}
\end{equation*}\]</span>
alkuperäinen otos, jonka otoskoko on <span class="math inline">\(n\)</span>. Kirjoitetaan havainto <span class="math inline">\(i\)</span> muodossa <span class="math inline">\((y_i, x_{i1}, x_{i2}, \ldots, x_{id}) = (y_i, \boldsymbol x_i)\)</span>, jossa <span class="math inline">\(\boldsymbol x_i\in\mathbb{R}^d\)</span>. Laske selitysaste <span class="math inline">\(R^2\)</span> alkuperäisestä otoksesta <span class="math inline">\(\left\{(y_1, \boldsymbol x_1), \ldots, (y_n, \boldsymbol x_n)\right\}\)</span>.</p></li>
<li><p>Merkitään selittäjää <span class="math inline">\(j\)</span> vastaavaa otosta notaatiolla <span class="math inline">\(\boldsymbol x_{\cdot j} = (x_{1j}, \ldots, x_{nj})^T\in\mathbb{R}^n\)</span>. Muodosta uusi <span class="math inline">\(n\)</span> kokoinen otos niin, että jokainen havainto vastaa alkuperäisen otoksen havaintoa <span class="math inline">\((y_i, \boldsymbol x_i)\)</span> muuten paitsi, että sarakevektori <span class="math inline">\(\boldsymbol x_{\cdot j}\)</span> on permutoitu.</p></li>
<li><p>Askeleen 2 mukaisia permutoituja otoksia on mahdollista muodostaa <span class="math inline">\(n!\)</span> kappaletta. Muodosta siis kaikki mahdolliset permutoidut otokset.</p></li>
<li><p>Laske selitysaste <span class="math inline">\(R_k^2\)</span> jokaiselle <span class="math inline">\(k = 1, \ldots, n!\)</span> permutoidulle otokselle.</p></li>
<li><p>Järjestä arvot <span class="math inline">\(R_1^2, \ldots, R_{n!}\)</span> suuruusjärjestykseen. Laske <span class="math inline">\(\left[(1 - \alpha)\times m\right]\)</span> järjestetty selitysaste. Tässä notaatio <span class="math inline">\([\cdot]\)</span> tarkoittaa pyöristämistä lähimpään kokonaislukuun. Tarkoitus on siis laskea selitysasteita <span class="math inline">\(\left\{R_1^2, \ldots, R_{n!}^2\right\}\)</span> vastaava <span class="math inline">\((1 - \alpha)\)</span>-otoskvantiili. Jos alkuperäisestä otoksesta laskettu <span class="math inline">\(R^2\)</span> on suurempi kuin laskettu otoskvantiili, niin nollahypoteesi <span class="math inline">\(H_0\)</span> hylätään.</p></li>
</ol>
<p>Huomautus <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#prp:permutation">6.1</a> pätee myös yllä kuvattuun permutaatiotestille parametrin merkitsevyydelle. Eli yleensä kaikkia mahdollisia permutoituja otoksia ei muodosteta.</p>
<p>Alla sovellamme permutaatiotestiä kertoimen merkitsevyydelle käytännössä.</p>
<div class="example">
<p><span id="exm:perm" class="example"><strong>Esimerkki 6.2  (Permutaatiotesti ja kertoimen merkitsevyys) </strong></span>Käytämme samaa dataa kuin esimerkissä <a href="moniulotteinen-lineaarinen-regressio.html#exm:fitreg">3.3</a>. Eli meillä on kuvitteellinen <span class="math inline">\(n = 10\)</span> kokoinen havaintoaineisto. Havainnot ovat toteumia satunnaisvektorista <span class="math inline">\((Y, X_1, X_2)\)</span>, jossa</p>
<ul>
<li><p><span class="math inline">\(Y = \text{voitto kuukaudessa tuhansina euroina}\)</span> (<code>profit</code>),</p></li>
<li><p><span class="math inline">\(X_1 = \text{mainosbudjetti kuukaudessa tuhansina euroina}\)</span> (<code>advertisement</code>) ja</p></li>
<li><p><span class="math inline">\(X_2 = \text{tuotteen hinta tuhansina euroina}\)</span> (<code>price</code>).</p></li>
</ul>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb237-1" tabindex="-1"></a>sale</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 -15.2          2.88  4.78 
##  2   4.97         7.88  2.27 
##  3  -8.51         4.09  3.39 
##  4   2.64         8.83  2.86 
##  5  13.8          9.40  0.515
##  6 -16.2          0.456 4.50 
##  7   5.91         5.28  1.23 
##  8   8.85         8.92  0.210
##  9   4.98         5.51  1.64 
## 10 -18.5          4.57  4.77</code></pre>
<p>Tavoitteenamme on testata lineaarisen regressiomallin
<span class="math display">\[\begin{equation*}
  \texttt{profit}_i = \beta_0 + \beta_1 \texttt{advertisement}_i + \beta_2 \texttt{price}_i + \varepsilon_i
\end{equation*}\]</span>
kertoimen <span class="math inline">\(\beta_1\)</span> merkitsevyyttä permutaatiotestillä. Asetamme merkitsevyystasoksi <span class="math inline">\(\alpha = 0.05\)</span>. Ennen kuin kirjoitamme permutaatiotestin algoritmin kokonaisuudessaan, näytämme tarkemmin, miten yksi permutoitu otos muodostetaan. Alla on taas tärkeää asettaa <code>replace = FALSE</code> funktiossa <code>sample()</code>.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb239-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-2" tabindex="-1"></a></span>
<span id="cb239-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-3" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb239-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb239-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-5" tabindex="-1"></a></span>
<span id="cb239-6"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-6" tabindex="-1"></a><span class="co"># Permutate observations of the advertisement</span></span>
<span id="cb239-7"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-7" tabindex="-1"></a>perm_advertisement <span class="ot">&lt;-</span> sale<span class="sc">$</span>advertisement[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">FALSE</span>)]</span>
<span id="cb239-8"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-8" tabindex="-1"></a></span>
<span id="cb239-9"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-9" tabindex="-1"></a><span class="co"># Replace original observations of the advertisement with the permuted sample</span></span>
<span id="cb239-10"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-10" tabindex="-1"></a>perm_sample <span class="ot">&lt;-</span> sale <span class="sc">%&gt;%</span></span>
<span id="cb239-11"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">advertisement =</span> perm_advertisement)</span>
<span id="cb239-12"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb239-12" tabindex="-1"></a>perm_sample</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 -15.2          5.51  4.78 
##  2   4.97         2.88  2.27 
##  3  -8.51         9.40  3.39 
##  4   2.64         0.456 2.86 
##  5  13.8          5.28  0.515
##  6 -16.2          8.92  4.50 
##  7   5.91         7.88  1.23 
##  8   8.85         8.83  0.210
##  9   4.98         4.57  1.64 
## 10 -18.5          4.09  4.77</code></pre>
<p>Taulukoissa <code>sale</code> ja <code>perm_sample</code> sarakkeet <code>profit</code> ja <code>price</code> ovat samat. Kuitenkin taulukossa <code>perm_sample</code> sarakkeen <code>advertisement</code> arvot ovat vaihtaneet paikkoja. Esimerkiksi taulukossa <code>sale</code>,
<span class="math display">\[\begin{equation*}
2.88 = \texttt{advertisement}_1
\end{equation*}\]</span>
mutta taulukossa <code>perm_sample</code>
<span class="math display">\[\begin{equation*}
  2.88 = \texttt{advertisement}_2.
\end{equation*}\]</span></p>
<p>Nyt olemme valmiita kirjoittamaan permutaatiotestin algoritmin askeleet 1–4. Selkeyden vuoksi toteutamme algoritmin <code>for</code> silmukan avulla.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-1" tabindex="-1"></a><span class="co"># Number of permutation samples</span></span>
<span id="cb241-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb241-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-3" tabindex="-1"></a></span>
<span id="cb241-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-4" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb241-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-5" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb241-6"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-6" tabindex="-1"></a></span>
<span id="cb241-7"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-7" tabindex="-1"></a><span class="co"># Create a vector for storing R^2</span></span>
<span id="cb241-8"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-8" tabindex="-1"></a>rsq_perm <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, m)</span>
<span id="cb241-9"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-9" tabindex="-1"></a></span>
<span id="cb241-10"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-10" tabindex="-1"></a><span class="co"># Compute R^2 from the original sample</span></span>
<span id="cb241-11"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-11" tabindex="-1"></a>sale_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> sale))</span>
<span id="cb241-12"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-12" tabindex="-1"></a>rsq_original <span class="ot">&lt;-</span> sale_lm_summary<span class="sc">$</span>r.squared</span>
<span id="cb241-13"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-13" tabindex="-1"></a></span>
<span id="cb241-14"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-14" tabindex="-1"></a></span>
<span id="cb241-15"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-15" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>m) {</span>
<span id="cb241-16"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-16" tabindex="-1"></a>  <span class="co"># Construct the ith permuted sample</span></span>
<span id="cb241-17"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-17" tabindex="-1"></a>  perm_advertisement <span class="ot">&lt;-</span> sale<span class="sc">$</span>advertisement[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">FALSE</span>)]</span>
<span id="cb241-18"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-18" tabindex="-1"></a>  </span>
<span id="cb241-19"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-19" tabindex="-1"></a>  perm_sample <span class="ot">&lt;-</span> sale <span class="sc">%&gt;%</span></span>
<span id="cb241-20"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-20" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">advertisement =</span> perm_advertisement)</span>
<span id="cb241-21"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-21" tabindex="-1"></a></span>
<span id="cb241-22"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-22" tabindex="-1"></a>  <span class="co"># Compute R^2 from the permuted sample</span></span>
<span id="cb241-23"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-23" tabindex="-1"></a>  perm_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price,</span>
<span id="cb241-24"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-24" tabindex="-1"></a>                                <span class="at">data =</span> perm_sample))</span>
<span id="cb241-25"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-25" tabindex="-1"></a>  rsq_perm[i] <span class="ot">&lt;-</span> perm_lm_summary<span class="sc">$</span>r.squared</span>
<span id="cb241-26"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb241-26" tabindex="-1"></a>}</span></code></pre></div>
<p>Vektori <code>rsq_perm</code> sisältää nyt permutaatioituja otoksia vastaavat selitysasteet <span class="math inline">\(R_1^2, \ldots, R_m^2\)</span>.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb242-1" tabindex="-1"></a><span class="fu">head</span>(rsq_perm)</span></code></pre></div>
<pre><code>## [1] 0.9437242 0.9171854 0.9195307 0.9292115 0.9339738 0.9354195</code></pre>
<p>Jäljellä on vielä algoritmin askel 5. Haluamme siis laskea <span class="math inline">\((1-\alpha)\)</span>-otoskvantiilin selitysasteista <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span>, kun <span class="math inline">\(\alpha = 0.05\)</span>. Tämän voi helposti suorittaa funktiolla <code>quantile()</code>.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb244-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb244-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb244-2" tabindex="-1"></a>rsq_perm_quantile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(rsq_perm, <span class="at">probs =</span> <span class="dv">1</span> <span class="sc">-</span> alpha)</span>
<span id="cb244-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb244-3" tabindex="-1"></a>rsq_perm_quantile</span></code></pre></div>
<pre><code>##       95% 
## 0.9569599</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb246-1" tabindex="-1"></a>rsq_original <span class="sc">&gt;</span> rsq_perm_quantile</span></code></pre></div>
<pre><code>##   95% 
## FALSE</code></pre>
<p>Alkuperäisestä otoksesta laskettu selitysaste on pienempi kuin yllä oleva <span class="math inline">\(0.95\)</span>-otoskvantiili, joten permutaatiotestin nollahypoteesia ei hylätä. Halutessasi voit myös laskea permutaatiotestin p-arvon vertaamalla kuinka suuri osuus selitysasteista <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span> on suurempaa kuin alkuperäisestä otoksesta laskettu selitysaste.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb248-1" tabindex="-1"></a><span class="fu">mean</span>(rsq_original <span class="sc">&lt;</span> rsq_perm)</span></code></pre></div>
<pre><code>## [1] 0.103</code></pre>
<p>Meillä ei siis ole näyttöä sen puolesta, että mainostus selittäisi voittojen määrää.</p>
<p>Permutaatiotestin tuloksiin liittyy satunnaisuutta, jos kaikkia <span class="math inline">\(n!\)</span> permutaatioita ei käytetä. Tämän vuoksi jokaisella algoritmin ajolla saat hieman erilaiset luottamusvälit. Tätä havainnollistaa myös kuvat <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:twoperm">6.1</a> ja <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:oneperm">6.2</a>.</p>

<div class="figure"><span style="display:block;" id="fig:twoperm"></span>
<img src="tidaja-book_files/figure-html/twoperm-1.png" alt="Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu \(m = 1000\) kappaleesta estimaatteja \(\left\{R_1^2, \ldots, R_m^2\right\}\), jotka laskettiin tässä esimerkissä permutoiduista otoksista. Vasemman kuvan sininen pystyviiva kuvaa \(0.95\)-otoskvantiilia estimaateista \(\left\{R_1^2, \ldots, R_m^2\right\}\). Oikeassa kuvassa permutaatiotesti suoritettiin uudelleen, jolloin saatiin hieman erilaiset \(m = 1000\) estimaattia (punainen histogrammi) ja otoskvantiili (punainen pystyviiva)." width="50%" /><img src="tidaja-book_files/figure-html/twoperm-2.png" alt="Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu \(m = 1000\) kappaleesta estimaatteja \(\left\{R_1^2, \ldots, R_m^2\right\}\), jotka laskettiin tässä esimerkissä permutoiduista otoksista. Vasemman kuvan sininen pystyviiva kuvaa \(0.95\)-otoskvantiilia estimaateista \(\left\{R_1^2, \ldots, R_m^2\right\}\). Oikeassa kuvassa permutaatiotesti suoritettiin uudelleen, jolloin saatiin hieman erilaiset \(m = 1000\) estimaattia (punainen histogrammi) ja otoskvantiili (punainen pystyviiva)." width="50%" />
<p class="caption">
Kuva 6.1: Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu <span class="math inline">\(m = 1000\)</span> kappaleesta estimaatteja <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span>, jotka laskettiin tässä esimerkissä permutoiduista otoksista. Vasemman kuvan sininen pystyviiva kuvaa <span class="math inline">\(0.95\)</span>-otoskvantiilia estimaateista <span class="math inline">\(\left\{R_1^2, \ldots, R_m^2\right\}\)</span>. Oikeassa kuvassa permutaatiotesti suoritettiin uudelleen, jolloin saatiin hieman erilaiset <span class="math inline">\(m = 1000\)</span> estimaattia (punainen histogrammi) ja otoskvantiili (punainen pystyviiva).
</p>
</div>

<div class="figure"><span style="display:block;" id="fig:oneperm"></span>
<img src="tidaja-book_files/figure-html/oneperm-1.png" alt="Sama tilanne kuin kuvassa 6.1. Nyt vain histogrammit ja otoskvantiilit ollaan piirretty samaan kuvaan. Tästä kuvasta nähdään selkeämmin, että eri permutaatiotestin ajoilla saadaan hieman erilaiset tulokset." width="672" />
<p class="caption">
Kuva 6.2: Sama tilanne kuin kuvassa <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:twoperm">6.1</a>. Nyt vain histogrammit ja otoskvantiilit ollaan piirretty samaan kuvaan. Tästä kuvasta nähdään selkeämmin, että eri permutaatiotestin ajoilla saadaan hieman erilaiset tulokset.
</p>
</div>
</div>
</div>
</div>
<div id="sec:bootstrap" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Uusiomenetelmä<a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#sec:bootstrap" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Luottamusväli on eräs vaihtoehtoinen menetelmä tilastollisen testaamisen rinnalla kuvaamaan parametriin liittyvää epävarmuutta. Tässä tapauksessa olemme kiinnostuneita luottamusväleistä lineaarisen mallin
<span class="math display">\[\begin{equation*}
  y_i = \beta_0  + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_d x_{id} + \varepsilon_i, \quad i\in\{1, \ldots, n\},
\end{equation*}\]</span>
vakiotermille <span class="math inline">\(\beta_0\)</span> ja kertoimille <span class="math inline">\(\beta_1, \ldots, \beta_j\)</span>. Muista, että parametrit <span class="math inline">\(\beta_j\)</span> ovat vakioita ja luottamusvälit ovat datasta riippuvia satunnaisia välejä. Eli <span class="math inline">\((1-\alpha)\)</span>-luottamusväli parametrille <span class="math inline">\(\beta_j\)</span> on satunnainen väli, joka sisältää todellisen parametrin arvon todennäköisyydellä <span class="math inline">\(1-\alpha\)</span>. Esimerkiksi <span class="math inline">\(0.95\)</span>-luottamusväli voidaan tulkita seuraavasti.</p>
<ol style="list-style-type: decimal">
<li><p>Otoksen
<span class="math display">\[\begin{equation*}
  \left\{\underbrace{(y_1, x_{11}, x_{12}, \ldots, x_{1d})}_{\text{$(d+1)$-ulotteinen havainto nro $1$}}, \ldots, \underbrace{(y_n, x_{n1}, x_{n2}, \ldots, x_{nd})}_{\text{$(d+1)$-ulotteinen havainto nro $n$}}\right\}
\end{equation*}\]</span>
avulla lasketaan <span class="math inline">\(0.95\)</span>-luottamusväli parametrille <span class="math inline">\(\beta_j\)</span>.</p></li>
<li><p>Oletetaan, että sinulla on saatavilla <span class="math inline">\(99\)</span> ylimääräistä kohdan 1 mukaista otosta. Lasket kaikista otoksista <span class="math inline">\(0.95\)</span>-luottamusvälin parametrille <span class="math inline">\(\beta_j\)</span>. Lopulta saat siis yhteensä sata <span class="math inline">\(0.95\)</span>-luottamusväliä.</p></li>
<li><p>Koska luottamusväli on satunnainen, niin jokainen väli on hieman erilainen. Lisäksi koska parametrin <span class="math inline">\(\beta_j\)</span> arvo on tuntematon, niin et tiedä, mitkä lasketuista väleistä peittävät parametrin todellisen arvon. Kuitenkin noin <span class="math inline">\(95\)</span> lasketuista luottamusväleistä sisältävät parametrin arvon <span class="math inline">\(\beta_j\)</span>. Kuva <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:conf">6.3</a> havainnollistaa <span class="math inline">\(0.95\)</span>-luottamusvälin tulkintaa.</p></li>
</ol>

<p>Tarkemmin luottamusvälin käsitettä voit kerrata kurssilta <em>Tilastotieteen perusteet</em>.</p>
<div class="figure"><span style="display:block;" id="fig:conf"></span>
<img src="tidaja-book_files/figure-html/conf-1.png" alt="Sata \(0.95\)-luottamusväliä parametrille \(\beta_j\). Siniset välit peittävät parametrin todellisen arvon ja punaiset eivät. Tässä tapauksessa viisi väliä sadasta eivät sisällä parametria \(\beta_j\)." width="672" />
<p class="caption">
Kuva 6.3: Sata <span class="math inline">\(0.95\)</span>-luottamusväliä parametrille <span class="math inline">\(\beta_j\)</span>. Siniset välit peittävät parametrin todellisen arvon ja punaiset eivät. Tässä tapauksessa viisi väliä sadasta eivät sisällä parametria <span class="math inline">\(\beta_j\)</span>.
</p>
</div>
<p>Tässä olemme kiinnostuneita luottamusvälin laskemisesta parametrille <span class="math inline">\(\beta_j\)</span> uusiomenetelmällä (eng: <em>bootstrap method</em>), joka on epäparametrinen menetelmä luottamusvälien muodostamiseen. Alla kuvaamme, kuinka <span class="math inline">\((1-\alpha)\)</span>-luottamusväli muodostetaan parametrille <span class="math inline">\(\beta_j\)</span> uusiomenetelmällä askel askeleelta.</p>
<ol style="list-style-type: decimal">
<li><p>Olkoon
<span class="math display">\[\begin{equation*}
  \overrightarrow{Z}^{(1)} = \left\{(y_1, x_{11}, x_{12}, \ldots, x_{1d}), \ldots, (y_n, x_{n1}, x_{n2}, \ldots, x_{nd})\right\}
\end{equation*}\]</span>
alkuperäinen otos, jonka otoskoko on <span class="math inline">\(n\)</span>. Muodosta uusi <span class="math inline">\(n\)</span> kokoinen otos <span class="math inline">\(\overrightarrow{Z}^{(2)}\)</span> palautusotannalla alkuperäisestä otoksesta <span class="math inline">\(\overrightarrow{Z}^{(1)}\)</span>. Uutta otosta <span class="math inline">\(\overrightarrow{Z}^{(2)}\)</span> kutsumme uusio-otokseksi (eng: <em>bootstrap sample</em>).</p>
<ul>
<li>Palautusotanta: valitset havaintoja (vektoreita) <span class="math inline">\((y_i, x_{i1}, x_{i2}, \ldots, x_{id})\)</span> alkuperäisestä otoksestä satunnaisesti niin, että sama havainto voidaan valita useampaan kertaan.</li>
</ul></li>
<li><p>Laske estimaatti <span class="math inline">\(\hat{\boldsymbol\beta}^{(2)} = \left(\hat\beta_0^{(2)}, \hat\beta_1^{(2)}, \ldots, \hat\beta_d^{(2)}\right)^T\)</span> muodostetusta uusio-otoksesta <span class="math inline">\(\overrightarrow{Z}^{(2)}\)</span>.</p></li>
<li><p>Toista edelliset askeleet <span class="math inline">\(m - 1\)</span> kertaa (esimerkiksi <span class="math inline">\(m = 1000\)</span>).</p>
<ul>
<li>Mitä suurempi <span class="math inline">\(m\)</span>, sitä parempi estimaatti luottamusvälille saadaan. Kuitenkin mitä suurempi <span class="math inline">\(m\)</span> arvo, sitä pidempään uusiomenetelmän suorittamisessa kestää tietokoneelta.</li>
</ul></li>
<li><p>Nappaa alkuperäisen otoksen <span class="math inline">\(\overrightarrow{Z}^{(1)}\)</span> avulla laskettu estimaatti <span class="math inline">\(\hat\beta_j^{(1)}\)</span> parametrille <span class="math inline">\(\beta_j\)</span>. Poimi myös uusio-otosten avulla lasketut estimaatit <span class="math inline">\(\hat\beta_j^{(2)}, \ldots, \hat\beta_j^{(m)}\)</span>.</p></li>
<li><p>Järjestä estimaatit <span class="math inline">\(\hat\beta_j^{(1)}, \hat\beta_j^{(2)}, \ldots, \hat\beta_j^{(m)}\)</span> suuruusjärjestykseen. Aseta luottamusvälin alapääksi <span class="math inline">\(\left[\frac{\alpha}{2}\times m\right]\)</span> järjestetty estimaatti. Aseta luottamusvälin yläpääksi <span class="math inline">\(\left[\frac{\alpha}{2}\times m\right]\)</span> järjestetty estimaatti. Tässä notaatio <span class="math inline">\([\cdot]\)</span> tarkoittaa pyöristämistä lähimpään kokonaislukuun. Tarkoitus on siis laskea estimaatteja <span class="math inline">\(\left\{\hat\beta_j^{(1)}, \hat\beta_j^{(2)}, \ldots, \hat\beta_j^{(m)}\right\}\)</span> vastaavat <span class="math inline">\(\alpha/2\)</span>- ja <span class="math inline">\((1 - \alpha/2)\)</span>-otoskvantiilit.</p></li>
</ol>
<p>Uusiomenetelmän ideana on siis luoda uusia otoksia alkuperäisestä otoksesta, joiden avulla laskettuja estimaatteja käytetään luottamusvälin muodostamiseen. Englanninkielinen nimitys <em>bootstrap</em> viittaakin itsensä nostamiseen ylös suosta vetämällä tarpeeksi kovaa omista kengännauhoista. Tämä on tietenkin fyysisesti mahdotonta mutta kuvaa hyvin sitä, kuinka uusiomenetelmässä luodaan uusia otoksia alkuperäistä. Alla sovellamme uusiomenetelmää käytännössä.</p>
<div class="example">
<p><span id="exm:unlabeled-div-43" class="example"><strong>Esimerkki 6.3  (Uusiomenetelmä) </strong></span>Käytämme samaa dataa kuin esimerkissä <a href="moniulotteinen-lineaarinen-regressio.html#exm:fitreg">3.3</a>. Eli meillä on kuvitteellinen <span class="math inline">\(n = 10\)</span> kokoinen havaintoaineisto. Havainnot ovat toteumia satunnaisvektorista <span class="math inline">\((Y, X_1, X_2)\)</span>, jossa</p>
<ul>
<li><p><span class="math inline">\(Y = \text{voitto kuukaudessa tuhansina euroina}\)</span> (<code>profit</code>),</p></li>
<li><p><span class="math inline">\(X_1 = \text{mainosbudjetti kuukaudessa tuhansina euroina}\)</span> (<code>advertisement</code>) ja</p></li>
<li><p><span class="math inline">\(X_2 = \text{tuotteen hinta tuhansina euroina}\)</span> (<code>price</code>).</p></li>
</ul>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb250-1" tabindex="-1"></a>sale</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 -15.2          2.88  4.78 
##  2   4.97         7.88  2.27 
##  3  -8.51         4.09  3.39 
##  4   2.64         8.83  2.86 
##  5  13.8          9.40  0.515
##  6 -16.2          0.456 4.50 
##  7   5.91         5.28  1.23 
##  8   8.85         8.92  0.210
##  9   4.98         5.51  1.64 
## 10 -18.5          4.57  4.77</code></pre>
<p>Tavoitteenamme on laskea <span class="math inline">\(0.95\)</span>-luottamusväli uusiomenetelmällä lineaarisen regressiomallin
<span class="math display">\[\begin{equation*}
  \texttt{profit}_i = \beta_0 + \beta_1 \texttt{advertisement}_i + \beta_2 \texttt{price}_i + \varepsilon_i
\end{equation*}\]</span>
kertoimelle <span class="math inline">\(\beta_2\)</span>. Ennen kuin kirjoitamme uusiomenetelmä algoritmin kokonaisuudessaan, kuvailemme tarkemmin muutamaa tärkeää askelta. Alkuperäisestä otoksesta laskettu estimaatti parametrille <span class="math inline">\(\beta_2\)</span> saadaan napattua <code>lm()</code> funktion tuottamasta muuttujasta.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb252-1" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb252-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb252-2" tabindex="-1"></a>sale_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> sale)</span>
<span id="cb252-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb252-3" tabindex="-1"></a></span>
<span id="cb252-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb252-4" tabindex="-1"></a><span class="co"># Inspect how to pick beta2</span></span>
<span id="cb252-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb252-5" tabindex="-1"></a><span class="fu">names</span>(sale_lm)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb254-1" tabindex="-1"></a>sale_lm<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##   (Intercept) advertisement         price 
##      5.885823      1.032046     -5.191414</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb256-1" tabindex="-1"></a>beta2 <span class="ot">&lt;-</span> sale_lm<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span>
<span id="cb256-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb256-2" tabindex="-1"></a>beta2</span></code></pre></div>
<pre><code>##     price 
## -5.191414</code></pre>
<p>Seuraavaksi näytämme, miten yksi uusio-otos muodostetaan. Uusio-otoksen voi muodostaa valitsemalla rivejä alkuperäisestä taulukosta käyttämällä funktiota <code>sample()</code>. On erittäin tärkeää, että funktiossa <code>sample()</code> asetat <code>replace = TRUE</code>. Tällöin on mahdollista valita sama havainto (eli rivi) useamman kerran.</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb258-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb258-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb258-2" tabindex="-1"></a>boot_sample <span class="ot">&lt;-</span> sale[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb258-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb258-3" tabindex="-1"></a>boot_sample</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    profit advertisement price
##     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1  -8.51         4.09  3.39 
##  2  -8.51         4.09  3.39 
##  3 -18.5          4.57  4.77 
##  4   4.97         7.88  2.27 
##  5 -16.2          0.456 4.50 
##  6  13.8          9.40  0.515
##  7   2.64         8.83  2.86 
##  8 -16.2          0.456 4.50 
##  9   4.98         5.51  1.64 
## 10 -18.5          4.57  4.77</code></pre>
<p>Vertaamalla muuttujia <code>sale</code> ja <code>boot_sample</code> huomataan, että kaikki taulukon <code>boot_sample</code> rivit ovat taulukon <code>sale</code> rivejä. Kuitenkin taulukossa <code>boot_sample</code> sama rivi voi esiintyä useamman kerran. Uusio-otoksesta saadaan laskettua estimaatti kertoimelle <span class="math inline">\(\beta_2\)</span> samaan tyyliin kuin alkuperäisen otoksen avulla.</p>
<p>Nyt olemme valmiita kirjoittamaan uusiomenetelmä algoritmin askeleet 1–4. Selkeyden vuoksi toteutamme algoritmin <code>for</code> silmukan avulla.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-1" tabindex="-1"></a><span class="co"># Number of repetitions (including the estimate from the original sample)</span></span>
<span id="cb260-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb260-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-3" tabindex="-1"></a></span>
<span id="cb260-4"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-4" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb260-5"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-5" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sale)</span>
<span id="cb260-6"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-6" tabindex="-1"></a></span>
<span id="cb260-7"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-7" tabindex="-1"></a><span class="co"># Create a vector for storing all the estimates</span></span>
<span id="cb260-8"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-8" tabindex="-1"></a>beta_boot <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, m)</span>
<span id="cb260-9"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-9" tabindex="-1"></a></span>
<span id="cb260-10"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-10" tabindex="-1"></a><span class="co"># Compute the parameter estimate from the original sample and store it</span></span>
<span id="cb260-11"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-11" tabindex="-1"></a>sale_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> sale)</span>
<span id="cb260-12"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-12" tabindex="-1"></a>beta_boot[<span class="dv">1</span>] <span class="ot">&lt;-</span> sale_lm<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span>
<span id="cb260-13"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-13" tabindex="-1"></a></span>
<span id="cb260-14"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-14" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>m) {</span>
<span id="cb260-15"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-15" tabindex="-1"></a>  <span class="co"># Construct the ith bootstrap sample and formulate the corresponding</span></span>
<span id="cb260-16"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-16" tabindex="-1"></a>  <span class="co"># linear regression model</span></span>
<span id="cb260-17"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-17" tabindex="-1"></a>  boot_sample <span class="ot">&lt;-</span> sale[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb260-18"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-18" tabindex="-1"></a>  boot_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(profit <span class="sc">~</span> advertisement <span class="sc">+</span> price, <span class="at">data =</span> boot_sample)</span>
<span id="cb260-19"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-19" tabindex="-1"></a>  </span>
<span id="cb260-20"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-20" tabindex="-1"></a>  <span class="co"># Compute the parameter estimate from the bootstrap sample and store it</span></span>
<span id="cb260-21"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-21" tabindex="-1"></a>  beta_boot[i] <span class="ot">&lt;-</span> boot_lm<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span>
<span id="cb260-22"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb260-22" tabindex="-1"></a>}</span></code></pre></div>
<p>Vektori <code>beta_boot</code> sisältää nyt alkuperäisellä otoksella lasketun estimaatin <span class="math inline">\(\hat\beta_2^{(1)}\)</span> parametrille <span class="math inline">\(\beta_2\)</span> ja vastaavat uusio-otoksista lasketut estimaatit <span class="math inline">\(\hat\beta_2^{(2)}, \ldots, \hat\beta_2^{(m)}\)</span>.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb261-1" tabindex="-1"></a><span class="fu">head</span>(beta_boot)</span></code></pre></div>
<pre><code>## [1] -5.191414 -7.197275 -5.941904 -5.981090 -6.093608 -3.877759</code></pre>
<p>Jäljellä on vielä algoritmin 5 askel. Eli haluamme laskea <span class="math inline">\(\alpha/2\)</span>- ja <span class="math inline">\((1 - \alpha/2)\)</span>-otoskvantiilit estimaateista <span class="math inline">\(\left\{\hat\beta_1^{(2)}, \hat\beta_2^{(2)}, \ldots, \hat\beta_2^{(m)}\right\}\)</span>, kun <span class="math inline">\(\alpha = 0.05\)</span>. Tämän voimme suorittaa helposti funktiolla <code>quantile()</code>.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb263-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb263-2"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb263-2" tabindex="-1"></a>boot_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(beta_boot, <span class="at">probs =</span> <span class="fu">c</span>(alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>))</span>
<span id="cb263-3"><a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#cb263-3" tabindex="-1"></a>boot_ci</span></code></pre></div>
<pre><code>##      2.5%     97.5% 
## -7.115774 -3.163906</code></pre>
<p>Nyt vektori <code>boot_ci</code> sisältää luottamusvälin ala- ja ylärajan. Eli parametrille <span class="math inline">\(\beta_2\)</span> saimme <span class="math inline">\(0.95\)</span>-luottamusväliksi <span class="math inline">\(\approx [-7.1, -3.2]\)</span>.</p>
<p>Huomaa, että uusio-otoksien muodostamiseen (koodissa <code>boot_sample</code>) liittyy satunnaisuutta. Tämän vuoksi jokaisella algoritmin ajolla saat hieman erilaiset luottamusvälit. Tätä havainnollistaa myös kuvat <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:twoboot">6.4</a> ja <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:oneboot">6.5</a>.</p>

<div class="figure"><span style="display:block;" id="fig:twoboot"></span>
<img src="tidaja-book_files/figure-html/twoboot-1.png" alt="Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu \(m = 1000\) kappaleesta estimaatteja \(\left\{\hat\beta_2^{(1)}, \hat\beta_2^{(2)}, \ldots, \hat\beta_2^{(m)}\right\}\), jotka laskettiin tässä esimerkissä. Vasemman kuvan siniset pystyviivat kuvaavat \(0.95\)-luottamusvälin ylä- ja alarajaa. Oikeassa kuvassa uusiomenetelmä suoritettiin uudelleen, jolloin saatiin hieman erilaiset \(m = 1000\) estimaattia (punainen histogrammi) ja luottamusväli (punaiset pystyviivat)." width="50%" /><img src="tidaja-book_files/figure-html/twoboot-2.png" alt="Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu \(m = 1000\) kappaleesta estimaatteja \(\left\{\hat\beta_2^{(1)}, \hat\beta_2^{(2)}, \ldots, \hat\beta_2^{(m)}\right\}\), jotka laskettiin tässä esimerkissä. Vasemman kuvan siniset pystyviivat kuvaavat \(0.95\)-luottamusvälin ylä- ja alarajaa. Oikeassa kuvassa uusiomenetelmä suoritettiin uudelleen, jolloin saatiin hieman erilaiset \(m = 1000\) estimaattia (punainen histogrammi) ja luottamusväli (punaiset pystyviivat)." width="50%" />
<p class="caption">
Kuva 6.4: Vasemmassa kuvassa näkyvä sininen histogrammi on muodostettu <span class="math inline">\(m = 1000\)</span> kappaleesta estimaatteja <span class="math inline">\(\left\{\hat\beta_2^{(1)}, \hat\beta_2^{(2)}, \ldots, \hat\beta_2^{(m)}\right\}\)</span>, jotka laskettiin tässä esimerkissä. Vasemman kuvan siniset pystyviivat kuvaavat <span class="math inline">\(0.95\)</span>-luottamusvälin ylä- ja alarajaa. Oikeassa kuvassa uusiomenetelmä suoritettiin uudelleen, jolloin saatiin hieman erilaiset <span class="math inline">\(m = 1000\)</span> estimaattia (punainen histogrammi) ja luottamusväli (punaiset pystyviivat).
</p>
</div>

<div class="figure"><span style="display:block;" id="fig:oneboot"></span>
<img src="tidaja-book_files/figure-html/oneboot-1.png" alt="Sama tilanne kuin kuvassa 6.4. Nyt vain histogrammit ja luottamusvälit ollaan piirretty samaan kuvaan. Tästä kuvasta nähdään selkeämmin, että eri uusiomenetelmän ajoilla saadaan hieman erilaiset tulokset." width="672" />
<p class="caption">
Kuva 6.5: Sama tilanne kuin kuvassa <a href="epäparametrisia-tilastollisia-menetelmiä-lineaariselle-regressiolle.html#fig:twoboot">6.4</a>. Nyt vain histogrammit ja luottamusvälit ollaan piirretty samaan kuvaan. Tästä kuvasta nähdään selkeämmin, että eri uusiomenetelmän ajoilla saadaan hieman erilaiset tulokset.
</p>
</div>
</div>
<div class="proposition">
<p><span id="prp:unlabeled-div-44" class="proposition"><strong>Huomautus 6.2  </strong></span>Uusiomenetelmää voidaan käyttää myös muunlaisten luottamusvälien laskemiseen. Esimerkiksi lineaarisen mallin ennustuksille voidaan laskea luottamusvälit käyttämällä uusiomenetelmää. Uusiomenetelmä ei ole myöskään sidoksissa lineaariseen regressioon vaan menetelmää voidaan käyttää muissa yhteyksissä. Kuitenkin tällä kurssilla käytämme uusiomenetelmää ainoastaan luottamusvälien laskemiseen lineaarisen mallin parametreille <span class="math inline">\(\beta_j\)</span>.</p>
<p>Huomaa myös, että oletuksen <a href="moniulotteinen-lineaarinen-regressio.html#def:whitenoise">3.1</a> alla parametreille <span class="math inline">\(\beta_j\)</span> voidaan laskea parametrinen luottamusväli. Tämä jätetään kuitenkin kurssin ulkopuolelle, koska parametristen luottamusvälien laskemisen filosofiaa käytiin kurssilla <em>Tilastotieteen perusteet</em>.</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="epäparametrisia-tilastollisia-testejä.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimoinnista.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
