<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Luku 3 Moniulotteinen lineaarinen regressio | Tilastotieteen ja data-analytiikan jatkokurssi</title>
  <meta name="description" content="Luku 3 Moniulotteinen lineaarinen regressio | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Luku 3 Moniulotteinen lineaarinen regressio | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Luku 3 Moniulotteinen lineaarinen regressio | Tilastotieteen ja data-analytiikan jatkokurssi" />
  
  
  

<meta name="author" content="Jaakko Pere" />


<meta name="date" content="2026-01-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="moniulotteiset-jakaumat.html"/>
<link rel="next" href="liitteet.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://mycourses.aalto.fi/course/view.php?id=48142" target="blank">ISM-C1002</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alustava kurssiohjelma</a></li>
<li class="chapter" data-level="1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html"><i class="fa fa-check"></i><b>1</b> R ohjelmointikielestä</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:inst"><i class="fa fa-check"></i><b>1.1</b> Ohjelmointikieli ja -ympäristö: asennus ja käyttö</a></li>
<li class="chapter" data-level="1.2" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:programming"><i class="fa fa-check"></i><b>1.2</b> Ohjelmoinnin opettelu</a></li>
<li class="chapter" data-level="1.3" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:packages"><i class="fa fa-check"></i><b>1.3</b> R-paketit</a></li>
<li class="chapter" data-level="1.4" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:demo"><i class="fa fa-check"></i><b>1.4</b> Data-analyysin askeleet</a></li>
<li class="chapter" data-level="1.5" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:markdown"><i class="fa fa-check"></i><b>1.5</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html"><i class="fa fa-check"></i><b>2</b> Moniulotteiset jakaumat</a>
<ul>
<li class="chapter" data-level="2.1" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:dep"><i class="fa fa-check"></i><b>2.1</b> Stokastinen riippumattomuus</a></li>
<li class="chapter" data-level="2.2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:rvec"><i class="fa fa-check"></i><b>2.2</b> Perusteet</a></li>
<li class="chapter" data-level="2.3" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:normal"><i class="fa fa-check"></i><b>2.3</b> Moniulotteinen normaalijakauma</a></li>
<li class="chapter" data-level="2.4" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:cond"><i class="fa fa-check"></i><b>2.4</b> Yhteisjakaumaan koodattu informaatio</a></li>
<li class="chapter" data-level="2.5" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:statistic"><i class="fa fa-check"></i><b>2.5</b> Tunnusluvuista</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html"><i class="fa fa-check"></i><b>3</b> Moniulotteinen lineaarinen regressio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#m%C3%A4%C3%A4ritelm%C3%A4-ja-oletukset"><i class="fa fa-check"></i><b>3.1</b> Määritelmä ja oletukset</a></li>
<li class="chapter" data-level="3.2" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#mallin-sovittaminen-ja-tulkinta"><i class="fa fa-check"></i><b>3.2</b> Mallin sovittaminen ja tulkinta</a></li>
<li class="chapter" data-level="3.3" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sovitteen-hyvyys-ja-ennustaminen"><i class="fa fa-check"></i><b>3.3</b> Sovitteen hyvyys ja ennustaminen</a></li>
<li class="chapter" data-level="3.4" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#mallin-ja-regressiokertoimien-merkitsevyys"><i class="fa fa-check"></i><b>3.4</b> Mallin ja regressiokertoimien merkitsevyys</a></li>
<li class="chapter" data-level="3.5" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#luottamus--ja-ennustev%C3%A4lit"><i class="fa fa-check"></i><b>3.5</b> Luottamus- ja ennustevälit</a></li>
<li class="chapter" data-level="3.6" data-path="moniulotteinen-lineaarinen-regressio.html"><a href="moniulotteinen-lineaarinen-regressio.html#sec:diagnostic"><i class="fa fa-check"></i><b>3.6</b> Mallidiagnostiikka</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="liitteet.html"><a href="liitteet.html"><i class="fa fa-check"></i><b>4</b> Liitteet</a>
<ul>
<li class="chapter" data-level="4.1" data-path="liitteet.html"><a href="liitteet.html#sec:vector"><i class="fa fa-check"></i><b>4.1</b> Vektoreista</a></li>
<li class="chapter" data-level="4.2" data-path="liitteet.html"><a href="liitteet.html#sec:matrix"><i class="fa fa-check"></i><b>4.2</b> Matriiseista</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="lähteet.html"><a href="lähteet.html"><i class="fa fa-check"></i>Lähteet</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Julkaistu bookdownin avulla</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tilastotieteen ja data-analytiikan jatkokurssi</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="moniulotteinen-lineaarinen-regressio" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Luku 3</span> Moniulotteinen lineaarinen regressio<a href="moniulotteinen-lineaarinen-regressio.html#moniulotteinen-lineaarinen-regressio" class="anchor-section" aria-label="Anchor link to header"></a></h1>



<p>Regressiomallit ovat eräitä tärkeimpiä ja eniten käytettyjä tilastollisia malleja. Regressioanalyysin tavoitteena on mallintaa selitettävän muuttujan (eng: <em>response variable</em>, <em>outcome variable</em>) riippuvuutta selittävistä muuttujista (eng: <em>explanatory variable</em>). Esimerkiksi selitettävä muuttuja voisi olla yrityksen voittojen suuruus ja selittäviä muuttujia voisivat olla markkinointi ja työntekijöiden määrä. Regressioanalyysi pyrkisi tässä tapauksessa vastaamaan seuraavanlaisiin kysymyksiin:</p>
<ul>
<li><p>Kuinka paljon voitot kasvavat/vähenevät euroissa, kun markkinointiin investoidaan <span class="math inline">\(r\)</span> euroa?</p></li>
<li><p>Entä kuinka paljon voitot kasvavat/vähenevät euroissa, jos palkkaamme <span class="math inline">\(m\)</span> työntekijää lisää?</p></li>
</ul>
<p>Tilanne regressioanalyysissä on yleensä seuraavanlainen. Saatavilla on <span class="math inline">\(n\)</span> kappaletta <span class="math inline">\((d + 1)\)</span>-ulotteisia havaintoja
<span class="math display">\[\begin{equation*}
  \left\{\underbrace{(y_1, x_{11}, x_{12}, \ldots, x_{1d})}_{\text{$d$-uloinen havainto nro $1$}}, \ldots, \underbrace{(y_n, x_{n1}, x_{n2}, \ldots, x_{nd})}_{\text{$d$-uloinen havainto nro $n$}}\right\}
\end{equation*}\]</span>
satunaisvektorista <span class="math inline">\((Y, X_1, \ldots, X_d)\)</span>, jossa ensimmäinen komponentti kuvaa selitettävää muuttujaa ja muut komponentit antavat selittävät muuttujat. Havaintoaineiston avulla sovitetaan regressiomalli, joka yleisesti ottaen voi olla muotoa
<span class="math display" id="eq:reggen">\[\begin{equation}
  \tag{3.1}
  y_i = f(x_{i1}, x_{i2}, \ldots, x_{id}) + \varepsilon_i,
  \quad i\in\{1, 2,\ldots, n\},
\end{equation}\]</span>
jossa <span class="math inline">\(f\)</span> mallintaa selittävän muuttujan ja selitettävien muuttujien välistä systemaattista suhdetta ja <span class="math inline">\(\varepsilon_i\)</span> on satunnainen virhetermi. Tästä johtuen yleensä selitettävän muuttujan arvo ei määräydy suoraan selittävistä muuttujista, vaan virhetermin vuoksi suhde on likimääräinen <span class="math inline">\(y_i \approx f(x_{i1}, x_{i2}, \ldots, x_{i2})\)</span>. Virhetermit <span class="math inline">\(\varepsilon_i\)</span> voivat kuvata esimerkiksi mittausvirheitä tai ilmiöön liittyvää satunnaisuutta.</p>
<p>Perinteisessä regressioanalyysissä analyytikko päättää funktion <span class="math inline">\(f\)</span> muodon ennen mallin sovittamista. Kuvassa <a href="moniulotteinen-lineaarinen-regressio.html#fig:regression">3.1</a> näkyy kolmen <span class="math inline">\(2\)</span>-ulotteisen kuvitteellisen havaintoaineiston
<span class="math display">\[\begin{equation*}
  \left\{(y_1, x_1), \ldots, (y_n, x_n)\right\}
\end{equation*}\]</span>
hajontakuviot.</p>
<div class="figure"><span style="display:block;" id="fig:regression"></span>
<img src="images/regression.jpg" alt="Kolmen \(2\)-ulotteisen havaintoaineiston hajontakuviot. Hajontakuvioiden muotojen perusteilla selitettävän muuttujan \(y\) ja selittävän muuttujan \(x\) riippuvuus on erilainen jokaisessa tapauksessa. Vasemmalla riippuvuus lineaarinen, keskellä neliöllinen ja oikealla eksponentiaalinen." width="1214" />
<p class="caption">
Kuva 3.1: Kolmen <span class="math inline">\(2\)</span>-ulotteisen havaintoaineiston hajontakuviot. Hajontakuvioiden muotojen perusteilla selitettävän muuttujan <span class="math inline">\(y\)</span> ja selittävän muuttujan <span class="math inline">\(x\)</span> riippuvuus on erilainen jokaisessa tapauksessa. Vasemmalla riippuvuus lineaarinen, keskellä neliöllinen ja oikealla eksponentiaalinen.
</p>
</div>
<p>Vasemmanpuoleisimpaan havaintoaineistoon voisi sopia yksiulotteinen lineaarinen regressiomalli, jossa funktio <span class="math inline">\(f\)</span> on muotoa
<span class="math display">\[\begin{equation*}
  f(x_{i}) = \beta_0 + \beta_1 x_i.
\end{equation*}\]</span>
Toisaalta keskimmäiseen havaintoaineistoon sopisi ehkäpä neliöllinen regressiomalli, jolloin
<span class="math display">\[\begin{equation*}
  f(x_i) = \alpha_0 + \alpha_1 x_i + \alpha_2 x_i^2.
\end{equation*}\]</span>
Oikeanpuoleiseen havaintoaineistoon voisi vastaavasti sovittaa eksponentiaalisen mallin
<span class="math display" id="eq:exp">\[\begin{equation}
  \tag{3.2}
  f(x_i) = \gamma_1 e^{\gamma_2 x_i}
\end{equation}\]</span>
hajontakuvion muodon perusteella. Kun mallin muoto on päätetty (lineaarinen, neliöllinen, …), niin mallin parametrit estimoidaan annetun otoksen avulla. Esimerkiksi sovittaessa lineaarista regressiomallia
<span class="math display">\[\begin{equation*}
  y_i = \beta_0 + \beta_1 x_i + \varepsilon_i
\end{equation*}\]</span>
tavoitteena on estimoida parametrit <span class="math inline">\(\beta_0\)</span> ja <span class="math inline">\(\beta_1\)</span> datan avulla. <strong>Huomaa, että estimaatti tarkoittaa datan perusteella laskettua parasta arvausta tietylle parametrille</strong>. Tämän vuoksi lasketut estimaatit erotetaan parametreista myös notaation kautta – yksiulotteisen lineaarisen regressiomallin parametrit ovat <span class="math inline">\(\beta_0\)</span> ja <span class="math inline">\(\beta_1\)</span> sekä niitä vastaavat estimaatit ovat <span class="math inline">\(\hat\beta_0\)</span> ja <span class="math inline">\(\hat\beta_1\)</span>.</p>
<p>Kun malli on sovitettu, niin estimaatteja <span class="math inline">\(\hat\beta_0\)</span> ja <span class="math inline">\(\hat\beta_1\)</span> voidaan tulkita. Mallin avulla voidaan tehdä myös ennustuksia tyyliin
<span class="math display">\[\begin{equation*}
  \tilde y = \hat\beta_0 + \hat\beta_1 \tilde x,
\end{equation*}\]</span>
jossa <span class="math inline">\(\tilde y_i\)</span> on mallin antama ennustus selittävän muuttujan arvolla <span class="math inline">\(\tilde x\)</span>.</p>
<p>Seuraavassa esimerkissä suoritetaan regressioanalyysin päävaiheet R:llä yksiulotteisen lineaarisen regression kautta. Eli samalla esimerkki toimii minimaalisena kertauksena yksiulotteisesta lineaarisesta regressiosta, joka käytiin kurssilla <em>Tilastotieteen perusteet</em>. Jos haluat kerrata yksiulotteisen lineaarisen regression teoriaa tarkemmin (pienimmän neliösumman estimointi, mallin selitysaste jne), niin palaa <em>Tilastotieteen perusteiden materiaaleihin</em>.</p>
<div class="example">
<p><span id="exm:simplereg" class="example"><strong>Esimerkki 3.1  (Yksiulotteinen lineaarinen regressio) </strong></span>Käsitellään jo tuttua aineistoa kehon dimensioiden mittauksista (katso esimerkki <a href="moniulotteiset-jakaumat.html#exm:body">2.1</a>). Tässä tapauksessa olemme kiinnostuneita vain muuttujista <code>TotalHeight</code> ja <code>ArmLength</code>. Tarkkaan ottaen haluamme ennustaa <span class="math inline">\(35\)</span> tuumaa (<span class="math inline">\(\approx 90\text{cm}\)</span> vastaa suurinpiirtein <span class="math inline">\(2\text{v}\)</span> taaperoa) pituisen ihmisen käsien pituuden.</p>
<p>Siivottu havaintoaineisto ollaan jo tallennettu muuttujaan <code>body</code>.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb83-1" tabindex="-1"></a>body</span></code></pre></div>
<pre><code>## # A tibble: 716 × 2
##    ArmLength TotalHeight
##        &lt;int&gt;       &lt;int&gt;
##  1        22          52
##  2        28          56
##  3        21          53
##  4        24          45
##  5        25          47
##  6        20          60
##  7        23          49
##  8        19          58
##  9        15          40
## 10        16          55
## # ℹ 706 more rows</code></pre>
<p>Aineisto siis sisältää <span class="math inline">\(n = 716\)</span> kappaletta <span class="math inline">\(2\)</span>-ulotteisia havaintoja <span class="math inline">\((y_i, x_i) = (\texttt{ArmLength}_i, \texttt{TotalHeight}_i)\)</span>, <span class="math inline">\(i\in\{1, 2, \ldots, n\}\)</span>. Kuvan <a href="moniulotteinen-lineaarinen-regressio.html#fig:height-scatter">3.2</a> hajontakuvion muodon perusteella yksiulotteisen lineaarisen regressiomallin
<span class="math display">\[\begin{equation*}
  y_i = \beta_0 + \beta_1 x_i + \varepsilon_i
\end{equation*}\]</span>
sovitus voisi olla järkevää.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb85-1" tabindex="-1"></a><span class="fu">plot</span>(body[, <span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>])</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:height-scatter"></span>
<img src="tidaja-book_files/figure-html/height-scatter-1.png" alt="Hajontakuvio muuttujista TotalHeight ja ArmLength." width="672" />
<p class="caption">
Kuva 3.2: Hajontakuvio muuttujista <code>TotalHeight</code> ja <code>ArmLength</code>.
</p>
</div>
<p>R:ssä lineaarisen regressiomallin voi sovittaa komennolla <code>lm()</code>. Kommennossa notaatiolla <code>y ~ x</code> (tilde) erotetaan havainnot selitettävästä muuttujasta ja selittävästä muuttujasta. Tulostamalla muuttujan, johon malli ollaan tallennettu, voi nähdä parametreja <span class="math inline">\(\beta_0\)</span> ja <span class="math inline">\(\beta_1\)</span> vastaavat pienimmän neliösumman estimaatit.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb86-1" tabindex="-1"></a>body_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(ArmLength <span class="sc">~</span> TotalHeight, <span class="at">data =</span> body)</span>
<span id="cb86-2"><a href="moniulotteinen-lineaarinen-regressio.html#cb86-2" tabindex="-1"></a>body_lm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ArmLength ~ TotalHeight, data = body)
## 
## Coefficients:
## (Intercept)  TotalHeight  
##      7.6499       0.2321</code></pre>
<p>Tulostuksen perusteella estimaateiksi saatiin <span class="math inline">\(\hat\beta_0\approx 7.65\)</span> ja <span class="math inline">\(\hat\beta_1\approx 0.23\)</span>. Tulkinnat parametreille ovat seuraavat:</p>
<ul>
<li><p><span class="math inline">\(\hat\beta_0\approx 7.65\)</span> (vakiotermi): Kun lapsen pituus on nolla, niin käsien pituus on keskimäärin <span class="math inline">\(7.65\)</span> tuumaa. Huomaa tässä tulkinnan epärealistisuus. On hyvä muistaa, että mikään malli ei ole täydellinen.</p></li>
<li><p><span class="math inline">\(\hat\beta_1\approx 0.23\)</span> (kulmakerroin): Kun ihmisen pituus kasvaa yhden tuuman, niin käsien pituus kasvaa keskimäärin <span class="math inline">\(0.23\)</span> tuumaa. Tässä tapauksessa kulmakertoimen merkki on luonnollinen, koska pidemmällä ihmisellä on yleensä myös pidemmät kädet.</p></li>
</ul>
<p>Regressiosuoran voi myös piirtää hajontakuvioon. Tätä varten täytyy päästä käsiksi regressiokertoimien arvoihin komennolla <code>body_lm$coefficients</code>. Kuvan <a href="moniulotteinen-lineaarinen-regressio.html#fig:height-reg">3.3</a> perusteella regressionmallin sovitus on hyvä visuaalisesti.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb88-1" tabindex="-1"></a><span class="fu">plot</span>(body[, <span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>])</span>
<span id="cb88-2"><a href="moniulotteinen-lineaarinen-regressio.html#cb88-2" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> body_lm<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">b =</span> body_lm<span class="sc">$</span>coefficients[<span class="dv">2</span>])</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:height-reg"></span>
<img src="tidaja-book_files/figure-html/height-reg-1.png" alt="Hajontakuvio muuttujista TotalHeight ja ArmLength sekä sovitetu regressiosuora." width="672" />
<p class="caption">
Kuva 3.3: Hajontakuvio muuttujista <code>TotalHeight</code> ja <code>ArmLength</code> sekä sovitetu regressiosuora.
</p>
</div>
<p>Mallin selitysaste <span class="math inline">\(R^2\)</span> kuvaa sovitteen hyvyyttä numeerisesti. Selitysaste on välillä <span class="math inline">\(0\leq R^2 \leq 1\)</span> ja mitä lähempänä <span class="math inline">\(R^2\)</span> arvo on lähellä ykköstä, sitä parempi sovite. Yhden muuttujan lineaarisen regression tapauksessa selitysaste on <span class="math inline">\(\hat\rho_{\texttt{ArmLength}, \texttt{TotalHeight}}^2\)</span>, eli otoskorrelaatio potenssiin kaksi, kun otoskorrelaatio ollaan laskettu havaintojen <span class="math inline">\(y_i = \texttt{ArmLength}_i\)</span> ja <span class="math inline">\(x_i = \texttt{TotalHeight}_i\)</span> avulla. Mallin selitysasteen näkee käyttämällä komentoa <code>summary()</code> (katso tulosteessa <code>Multiple R-squared</code>).</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb89-1" tabindex="-1"></a><span class="fu">summary</span>(body_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ArmLength ~ TotalHeight, data = body)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.486  -2.469  -0.395   2.157  53.477 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  7.64993    0.69926   10.94   &lt;2e-16 ***
## TotalHeight  0.23207    0.01409   16.47   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.58 on 714 degrees of freedom
## Multiple R-squared:  0.2753, Adjusted R-squared:  0.2743 
## F-statistic: 271.3 on 1 and 714 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Selityste ei ole kovin korkea (<span class="math inline">\(R^2\approx 0.28\)</span>), mikä todennäköisesti johtuu havaintoaineiston muutamasta poikkeavasta havainnosta. Tästä huolimatta mallin avulla ennustamme käsien pituuden, kun henkilön pituus on <span class="math inline">\(35\)</span> tuumaa. Ennustuksen voi suorittaa kätevästi saatujen estimaattien <span class="math inline">\(\hat\beta_0\)</span> ja <span class="math inline">\(\hat\beta_0\)</span> arvoja käyttäen.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="moniulotteinen-lineaarinen-regressio.html#cb91-1" tabindex="-1"></a>x_tilde <span class="ot">&lt;-</span> <span class="dv">35</span></span>
<span id="cb91-2"><a href="moniulotteinen-lineaarinen-regressio.html#cb91-2" tabindex="-1"></a>body_lm<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> body_lm<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">*</span> x_tilde</span></code></pre></div>
<pre><code>## (Intercept) 
##    15.77253</code></pre>
<p>Eli <span class="math inline">\(35\)</span> tuuman pituisen ihmisen käsien pituudeksi ennustetaan <span class="math inline">\(15.77\)</span> tuumaa.</p>
</div>
<p>Tämän kurssin kannalta tärkein regressiomenetelmä on nimenomaan lineaarinen regressio. Laajennamme kuitenkin esimerkissä <a href="moniulotteinen-lineaarinen-regressio.html#exm:simplereg">3.1</a> käsiteltyä yksiulotteista lineaarista regressiota (eng: <em>simple linear regression</em>) monen selittävän muuttujan tapaukseen. Vaikka lineaarinen regressio saattaa alkusilmäyksellä vaikuttaa liian yksinkertaiselta mallilta käytännön sovelluksiin, niin näin ei kuitenkaan ole:</p>
<ul>
<li><p>Ensinnäkin monet epälineaariset mallit kuten eksponentiaalinen ja neliöllinen malli voidaan sovittaa lineaarisen regression avulla.</p>
<ul>
<li><p>Jo kurssilla <em>Johdatus data-analytiikkaan</em> todettiin, että eksponentiaalisen mallin parametrit (kaavan <a href="moniulotteinen-lineaarinen-regressio.html#eq:exp">(3.2)</a> parametrit <span class="math inline">\(\gamma_1\)</span> ja <span class="math inline">\(\gamma_2\)</span>) voidaan estimoida sovittamalla yksiulotteinen lineaarinen regressiomalli muunnetulle datalle.</p></li>
<li><p>Lisäksi viikon 4 tehtävässä 3 näemme kuinka neliöllinen malli voidaan sovittaa moniulotteisen lineaarisen regression avulla.</p></li>
</ul></li>
<li><p>Usein tavoitteena on löytää mahdollisimman yksinkertainen malli, joka kuitenkin mallintaa alla olevaa ilmiötä mahdollisimman hyvin (eng: <em>parsimonious model</em>). Tämän vuoksi lineaarinen regressio on käytännön kannalta erittäin hyödyllinen monessa eri sovelluksessa. Esimerkkinä voimme mainita viikon 4 tehtävän 2, jossa tuottoja mallinetaan muilla taustatekijöillä.</p></li>
</ul>
<p>Lisäksi tilastollisen mallintamisen opettelun näkökulmasta lineaarinen regressio on erinomainen lähtökohta – monet monimutkaisemmat mallit (aikasarjamallinnus, neuroverkot, …) on vaikea ymmärtää ilman perustaitoja.</p>
<div id="määritelmä-ja-oletukset" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Määritelmä ja oletukset<a href="moniulotteinen-lineaarinen-regressio.html#m%C3%A4%C3%A4ritelm%C3%A4-ja-oletukset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Kuten luvun esittelyssä, oletetaan että saatavilla on <span class="math inline">\(n\)</span> kappaletta <span class="math inline">\((d+1)\)</span>-ulotteisia havaintoja
<span class="math display">\[\begin{equation*}
  \left\{\underbrace{(y_1, x_{11}, x_{12}, \ldots, x_{1d})}_{\text{$d$-uloinen havainto nro $1$}}, \ldots, \underbrace{(y_n, x_{n1}, x_{n2}, \ldots, x_{nd})}_{\text{$d$-uloinen havainto nro $n$}}\right\}
\end{equation*}\]</span>
satunaisvektorista <span class="math inline">\((Y, X_1, \ldots, X_d)\)</span>, jossa ensimmäinen komponentti antaa selitettävän muuttujan havainnot ja muut komponentit antavat selittävien muuttujien havainnot. Selittäviä muuttujia on siis <span class="math inline">\(d\)</span> kappaletta. Moniulotteisessa lineaarisessa regressiossa oletetaan seuraavanlainen suhde selitettävän ja selittävien muuttujien välillä,
<span class="math display" id="eq:regression">\[\begin{equation}
  \tag{3.3}
  \begin{split}
    y_i &amp;= \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_d x_{id} + \varepsilon_i \\
    &amp;= \beta_0 + \left(\sum_{j = 1}^d \beta_j x_{ij}\right) + \varepsilon_i,
    \quad i\in\{1, 2,\ldots, n\},
  \end{split}
\end{equation}\]</span>
jossa <span class="math inline">\(\varepsilon_i\)</span> ovat satunnaisia virhetermejä. Yllä oleva malli seuraa siis yhtälön <a href="moniulotteinen-lineaarinen-regressio.html#eq:reggen">(3.1)</a> yleisestä regressiomallista valinnalla <span class="math inline">\(f(x_{i1}, x_{i2}, \ldots, x_{id}) = \beta_0 + \sum_{j = 1}^d \beta_j x_{ij}\)</span>.</p>
<p>Tähän mennessä emme ole käsitelleet virhetermeihin <span class="math inline">\(\varepsilon_i\)</span> liittyviä oletuksia sen tarkemmin. Tästä eteenpäin kuitenkin oletamme, että lineaarisen regressiomallin virhetermit ovat valkoista kohinaa ellei toisin sanota.</p>
<div class="definition">
<p><span id="def:whitenoise" class="definition"><strong>Määritelmä 3.1  (Valkoinen kohina) </strong></span>Satunnaismuuttujat <span class="math inline">\(\varepsilon_1, \varepsilon_2, \ldots, \varepsilon_n\)</span> ovat valkoista kohinaa, jos</p>
<ol style="list-style-type: decimal">
<li><p>jokainen satunnaismuuttuja <span class="math inline">\(\varepsilon_i\)</span> noudattaa normaalijakaumaa <span class="math inline">\(\varepsilon_i\sim N(0, \sigma^2)\)</span> (havainnosta <span class="math inline">\(i\)</span> riippumattomilla) odotusarvolla <span class="math inline">\(0\)</span> ja varianssilla <span class="math inline">\(\sigma^2 &gt; 0\)</span>, ja</p></li>
<li><p>satunnaismuuttujat <span class="math inline">\(\varepsilon_1, \varepsilon_2, \ldots, \varepsilon_n\)</span> ovat riippumattomia.</p></li>
</ol>
</div>
<p>Yllä olevan määritelmän oletuksia voidaan monissa tapauksissa lieventää. Esimerkiksi oletus normaalijakautuneisuudesta ei ole aina tarpeen tai edes realistinen. Kuitenkin mukavuussyistä rajoitumme määritelmän <a href="moniulotteinen-lineaarinen-regressio.html#def:whitenoise">3.1</a> mukaisiin oletuksiin virhetermeille <span class="math inline">\(\varepsilon_i\)</span>. Virhetermien oletuksista seuraa esimerkiksi seuraavaa:</p>
<ol style="list-style-type: decimal">
<li><p>Virhetermin <span class="math inline">\(\varepsilon_i\)</span> varianssi ei riipu selittävien muuttujien havainnoista <span class="math inline">\((x_{i1}, x_{i2}, \ldots, x_{id})\)</span>. Jos näin kuitenkin olisi, niin mallia kutsuttaisiin heteroskedastiseksi tai erivarianssiseksi (eng: <em>heteroskedastic</em>).</p></li>
<li><p>Mille tahansa parille virhetermejä <span class="math inline">\(\varepsilon_i\)</span> ja <span class="math inline">\(\varepsilon_j\)</span> pätee <span class="math inline">\(\mathrm{Cov}\left(\varepsilon_i, \varepsilon_j\right) = 0\)</span>, kun <span class="math inline">\(i\neq j\)</span>.</p></li>
</ol>
<p>Tilastollisessa mallintamisessa on aina tärkeää miettiä ennen itse analyysiä, pätevätkö mallin oletukset. Tätä kutsutaan mallidiagnostiikaksi, jota käsitellään tarkemmin luvussa <a href="moniulotteinen-lineaarinen-regressio.html#sec:diagnostic">3.6</a>.</p>
<p>Lineaarisen regressiomallin määritelmä voidaan myös kirjoittaa hyödyntäen matriisinotaatiota. Ensin kerätään havainnot selitettävästä muuttujasta omaan vektoriinsa, havainnot selittävistä muuttujista omaan matriisiin (jossa 1. sarake on vain ykkösiä), parametrit <span class="math inline">\(\beta_j\)</span> omaan vektoriinsa ja virhetermit omaan vektoriinsa
<span class="math display">\[\begin{equation*}
\begin{split}
  &amp;\boldsymbol y =
  \begin{pmatrix}
    y_1 \\ y_2 \\ \vdots \\ y_n
  \end{pmatrix}\in\mathbb{R}^n, \quad
  \boldsymbol X =
  \begin{pmatrix}
    1 &amp; x_{11} &amp; x_{12} &amp; \cdots &amp; x_{1d} \\
    1 &amp; x_{21} &amp; x_{22} &amp; \cdots &amp; x_{2d} \\
    \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
    1 &amp; x_{n1} &amp; x_{n2} &amp; \cdots &amp; x_{nd}
  \end{pmatrix} \in\mathbb{R}^{n\times (d+1)}, \\
  &amp;\boldsymbol\beta =
  \begin{pmatrix}
    \beta_0 \\ \beta_1 \\ \vdots \\ \beta_d
  \end{pmatrix}\in\mathbb{R}^{d+1},\ \text{ja}\quad
  \boldsymbol\varepsilon =
  \begin{pmatrix}
    \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n
  \end{pmatrix}\in\mathbb{R}^n.
  \end{split}
\end{equation*}\]</span>
Eli jos ei oteta huomioon ensimmäistä saraketta, niin matriisin <span class="math inline">\(\boldsymbol X\)</span> sarake <span class="math inline">\(j\)</span> kuvaa havaintoja selitettävästä muuttujasta <span class="math inline">\(X_j\)</span>, <span class="math inline">\(j\in\{1,\ldots, d\}\)</span>. Matriisin <span class="math inline">\(\boldsymbol X\)</span> ensimmäinen sarake ykkösiä ottaa huomioon sen, että parametri <span class="math inline">\(\beta_0\)</span> otetaan huomioon oikealla tavalla suoritettaessa matriisikertolaskut. Yhtälön <a href="moniulotteinen-lineaarinen-regressio.html#eq:regression">(3.3)</a> määritelmä voidaan siis kirjoittaa matriisikertolaskuilla muodossa
<span class="math display" id="eq:regmatrix">\[\begin{equation}
\tag{3.4}
  \boldsymbol y = \boldsymbol X \boldsymbol\beta + \boldsymbol\varepsilon.
\end{equation}\]</span></p>
<p>Alla on vielä käytännönläheinen esimerkki siitä, miten yrityksen data-analyytikko voisi muotoilla lineaarisen regressiomallinnustehtävän.</p>
<div class="example">
<p><span id="exm:regconstruction" class="example"><strong>Esimerkki 3.2  (Esimerkki) </strong></span>Oletetaan, että yritys haluaa mallintaa tuotteen myynnistä saatavaa kuukausittaista voittoa <span class="math inline">\(Y\)</span> (tuhansissa euroissa) kahden keskeisen tekijän perusteella. Yrityksen aiempien analyysien mukaan voittoon vaikuttavat erityisesti
seuraavat muuttujat:</p>
<ul>
<li><p><span class="math inline">\(X_1 = \text{Mainosbudjetti kuukaudessa (tuhansina euroina)}\)</span></p></li>
<li><p><span class="math inline">\(X_2 = \text{Tuotteen hinta (tuhansina euroina)}\)</span></p></li>
</ul>
<p>Yrityksellä on kymmenen eri kuukauden myyntidata
<span class="math display">\[\begin{equation*}
  \begin{split}
  &amp;(y_i, x_{i1}, x_{i2}) = (\text{voitto $i.$kk}, \text{mainosbudjetti $i.$kk}, \text{tuotteen hinta $i.$kk}), \\
  &amp;i\in\{1,2, \ldots, 10\}
  \end{split}
\end{equation*}\]</span>
liittyen satunnaisvektoriin <span class="math inline">\((Y, X_1, X_2)\)</span>. Yrityksen data-analyytikko haluaa siis sovittaa lineaarisen regressiomallin
<span class="math display">\[\begin{equation*}
  y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \varepsilon_i
\end{equation*}\]</span>
tai vielä monisanaisemmin
<span class="math display">\[\begin{equation*}
  \texttt{voitto}_i = \beta_0 + \beta_1 \texttt{mainostus}_i + \beta_2 \texttt{hinta}_i + \varepsilon_i.
\end{equation*}\]</span>
Mallinsovitustehtävän voisi muotoilla yhtälön <a href="moniulotteinen-lineaarinen-regressio.html#eq:regmatrix">(3.4)</a> mukaan määrittelemällä oikeanlaiset matriisit ja vektorit, kun otoskoko on <span class="math inline">\(n = 10\)</span> ja selittäviä muuttujia on <span class="math inline">\(d = 2\)</span>,
<span class="math display">\[\begin{equation*}
\begin{split}
  &amp;\boldsymbol y =
  \begin{pmatrix}
    y_1 \\ y_2 \\ \vdots \\ y_{10}
  \end{pmatrix}\in\mathbb{R}^{10}, \quad
  \boldsymbol X =
  \begin{pmatrix}
    1 &amp; x_{11} &amp; x_{12} \\
    1 &amp; x_{21} &amp; x_{22} \\
    \vdots &amp; \vdots &amp; \vdots \\
    1 &amp; x_{n1} &amp; x_{n2} \\
  \end{pmatrix} \in\mathbb{R}^{10\times 3}, \\
  &amp;\boldsymbol\beta =
  \begin{pmatrix}
    \beta_0 \\ \beta_1 \\ \beta_2
  \end{pmatrix}\in\mathbb{R}^{3},\ \text{ja}\quad
  \boldsymbol\varepsilon =
  \begin{pmatrix}
    \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_{10}
  \end{pmatrix}\in\mathbb{R}^{10}.
  \end{split}
\end{equation*}\]</span></p>
</div>
</div>
<div id="mallin-sovittaminen-ja-tulkinta" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Mallin sovittaminen ja tulkinta<a href="moniulotteinen-lineaarinen-regressio.html#mallin-sovittaminen-ja-tulkinta" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="sovitteen-hyvyys-ja-ennustaminen" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Sovitteen hyvyys ja ennustaminen<a href="moniulotteinen-lineaarinen-regressio.html#sovitteen-hyvyys-ja-ennustaminen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="mallin-ja-regressiokertoimien-merkitsevyys" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Mallin ja regressiokertoimien merkitsevyys<a href="moniulotteinen-lineaarinen-regressio.html#mallin-ja-regressiokertoimien-merkitsevyys" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="luottamus--ja-ennustevälit" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Luottamus- ja ennustevälit<a href="moniulotteinen-lineaarinen-regressio.html#luottamus--ja-ennustev%C3%A4lit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="sec:diagnostic" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Mallidiagnostiikka<a href="moniulotteinen-lineaarinen-regressio.html#sec:diagnostic" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="moniulotteiset-jakaumat.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="liitteet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
