<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Luku 2 Moniulotteiset jakaumat | Tilastotieteen ja data-analytiikan jatkokurssi</title>
  <meta name="description" content="Luku 2 Moniulotteiset jakaumat | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Luku 2 Moniulotteiset jakaumat | Tilastotieteen ja data-analytiikan jatkokurssi" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Luku 2 Moniulotteiset jakaumat | Tilastotieteen ja data-analytiikan jatkokurssi" />
  
  
  

<meta name="author" content="Jaakko Pere" />


<meta name="date" content="2026-01-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r-ohjelmointikielestä.html"/>
<link rel="next" href="lähteet.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://mycourses.aalto.fi/course/view.php?id=48142" target="blank">ISM-C1002</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alustava kurssiohjelma</a></li>
<li class="chapter" data-level="1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html"><i class="fa fa-check"></i><b>1</b> R ohjelmointikielestä</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:inst"><i class="fa fa-check"></i><b>1.1</b> Ohjelmointikieli ja -ympäristö: asennus ja käyttö</a></li>
<li class="chapter" data-level="1.2" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:programming"><i class="fa fa-check"></i><b>1.2</b> Ohjelmoinnin opettelu</a></li>
<li class="chapter" data-level="1.3" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:packages"><i class="fa fa-check"></i><b>1.3</b> R-paketit</a></li>
<li class="chapter" data-level="1.4" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:demo"><i class="fa fa-check"></i><b>1.4</b> Data-analyysin askeleet</a></li>
<li class="chapter" data-level="1.5" data-path="r-ohjelmointikielestä.html"><a href="r-ohjelmointikielestä.html#sec:markdown"><i class="fa fa-check"></i><b>1.5</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html"><i class="fa fa-check"></i><b>2</b> Moniulotteiset jakaumat</a>
<ul>
<li class="chapter" data-level="2.1" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:dep"><i class="fa fa-check"></i><b>2.1</b> Stokastinen riippumattomuus</a></li>
<li class="chapter" data-level="2.2" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:rvec"><i class="fa fa-check"></i><b>2.2</b> Perusteet</a></li>
<li class="chapter" data-level="2.3" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:normal"><i class="fa fa-check"></i><b>2.3</b> Moniulotteinen normaalijakauma</a></li>
<li class="chapter" data-level="2.4" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:cond"><i class="fa fa-check"></i><b>2.4</b> Ehdolliset jakaumat ja reunajakaumat</a></li>
<li class="chapter" data-level="2.5" data-path="moniulotteiset-jakaumat.html"><a href="moniulotteiset-jakaumat.html#sec:statistic"><i class="fa fa-check"></i><b>2.5</b> Tunnusluvuista</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="lähteet.html"><a href="lähteet.html"><i class="fa fa-check"></i>Lähteet</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Julkaistu bookdownin avulla</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tilastotieteen ja data-analytiikan jatkokurssi</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="moniulotteiset-jakaumat" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Luku 2</span> Moniulotteiset jakaumat<a href="moniulotteiset-jakaumat.html#moniulotteiset-jakaumat" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Kurssilla <em>Tilastotieteen perusteet</em> käsiteltiin (yksiulotteiset) satunnaismuuttujat. Satunnaismuuttuja on funktio, joka saa lukuarvon (kokonaislukuluku <span class="math inline">\(\mathbb{Z}\)</span>, rationaaliluku <span class="math inline">\(\mathbb{Q}\)</span>, Reaaliluku <span class="math inline">\(\mathbb{R}\)</span>) satunnaisilmiön toteuman perusteella. Satunnaismuuttuja voi olla diskreetti kuten <span class="math inline">\(X_1 = \mathrm{nopanheiton\  tulos}\)</span> tai jatkuva kuten <span class="math inline">\(X_2 = \mathrm{Bussin\ saapumisaika\ pysäkille}\)</span>. Satunnaismuuttujan <span class="math inline">\(Y\)</span> käyttäytymistä mallintaa sen jakauma <span class="math inline">\(\mathbb{P}\left(Y\in A\right)\)</span>, jossa <span class="math inline">\(\{Y\in A\}\)</span> on mahdollinen tapahtuma. Esimerkiksi tapahtumaa “nopanheiton tulos on 1 tai 5” vastaava todennäköisyys on <span class="math inline">\(\mathbb{P}\left(X_1\in \{2, 5\}\right) = 2/6 = 1/3\)</span>, kunhan noppa on reilu. Kaiken informaation satunnaismuuttujan <span class="math inline">\(Y\)</span> jakaumasta sisältää kertymäfunktio <span class="math inline">\(F_Y(y) = \mathbb{P}\left(Y \leq y\right)\)</span>. Jos satunnaismuuttuja <span class="math inline">\(Y\)</span> on diskreetti, niin sen kertymäfunktio voidaan kirjoittaa pistetodennäköisyysfunktion <span class="math inline">\(p_Y(x) = \mathbb{P}\left(Y = x\right)\)</span> avulla
<span class="math display" id="eq:discrete-uni-cdf">\[\begin{equation}
  \tag{2.1}
  F_Y(y) = \sum_{x\leq y} p_Y(x).
\end{equation}\]</span>
Jos taas satunnaismuuttuja <span class="math inline">\(Y\)</span> on jatkuva, niin sen kertymäfunktio voidaan kirjoittaa tiheysfunktion <span class="math inline">\(f_Y(x)\)</span> avulla integraalina
<span class="math display" id="eq:continuous-uni-cdf">\[\begin{equation*}
  \tag{2.2}
  F_Y(y) = \int_{-\infty}^{y} f_Y(x)\, \mathrm{d}x.
\end{equation*}\]</span>
Jakauman sijainnnista ja hajonnasta antavat tietoa teoreettiset suureet kuten odotusarvo <span class="math inline">\(\mathbb{E}\left(Y\right)\)</span> ja varianssi <span class="math inline">\(\mathrm{Var}\left(Y\right) = \mathbb{E}\left(\left(Y - \mathbb{E}\left(Y\right)\right)^2\right)\)</span>. Myös muita jakaumaa kuvaavia teoreettisia suureita on olemassa: <em>vinous</em>, <em>huipukkuus</em>, <em>kvantiilit</em>, <span class="math inline">\(\ldots\)</span> Tilastotieteen sovelluksissa on kuitenkin yleensä saatavilla vain otos <span class="math inline">\(y_1,\ldots, y_n\)</span> satunnaismuuttujasta <span class="math inline">\(Y\)</span> eikä satunnaismuuttujan teoreettisia ominaisuuksia tunneta. Tällöin satunnaismuuttujan <span class="math inline">\(Y\)</span> jakaumaa vastaavat teoreettiset suureet täytyy estimoida otoksen avulla. Esimerkiksi odotusarvo voidaan estimoida keskiarvolla
<span class="math display">\[\begin{equation*}
  \bar y = \frac{1}{n}\sum_{i = 1}^n y_i
\end{equation*}\]</span>
ja varianssi voidaan estimoida otosvarianssilla
<span class="math display">\[\begin{equation*}
  s_Y^2 = \frac{1}{n-1}\sum_{i = 1}^n\left(y_i - \bar  y\right)^2.
\end{equation*}\]</span>
Kertaa tarvittaessa edellämainittuja asioita kurssilta <em>Tilastotieteen perusteet</em>.</p>
<p>Yllä kuvattu asetelma on usein liian yksinkertainen käytännön datatietieteen sovelluksissa, sillä monesti dataa on saatavilla useista eri muuttujista.</p>

<div class="example">
<p><span id="exm:body" class="example"><strong>Esimerkki 2.1  (Moniulotteinen aineisto) </strong></span>Taulukossa <a href="moniulotteiset-jakaumat.html#tab:body">2.1</a> näkyy neliulotteinen aineisto ihmisen kehon eri osien mittauksista (yksikkö: tuuma). Kaikki mitatut muuttujat <code>ShoulderWidth</code>, <code>Belly</code>, <code>ArmLength</code> ja <code>TotalHeight</code> ovat tässä tapauksessa jatkuvia. Tuntuisi luonnolliselta, että muuttujien välillä on riippuvuussuhteita. Esimerkiksi ehkä pidemmällä ihmisellä on pidemmät kädet? Jos näin on, niin menetämme informaatiota analysoidessa muuttujia erikseen.</p>
<table>
<caption><span id="tab:body">Taulukko 2.1: </span>Neliulotteinen aineisto ihmisen kehon dimensioista. Rivi vastaa yhtä havaintoa (ihmistä) ja sarake vastaa yhtä muuttujaa.</caption>
<thead>
<tr class="header">
<th align="right">ShoulderWidth</th>
<th align="right">Belly</th>
<th align="right">ArmLength</th>
<th align="right">TotalHeight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">18</td>
<td align="right">18</td>
<td align="right">22</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">22</td>
<td align="right">18</td>
<td align="right">28</td>
<td align="right">56</td>
</tr>
<tr class="odd">
<td align="right">18</td>
<td align="right">14</td>
<td align="right">21</td>
<td align="right">53</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">11</td>
<td align="right">24</td>
<td align="right">45</td>
</tr>
<tr class="odd">
<td align="right">14</td>
<td align="right">13</td>
<td align="right">25</td>
<td align="right">47</td>
</tr>
<tr class="even">
<td align="right">19</td>
<td align="right">14</td>
<td align="right">20</td>
<td align="right">60</td>
</tr>
</tbody>
</table>
<p>Hyvä vaihtoehto visualisoida dataa voisi olla hajontakuvio. Kuvaajassa olisi kuitenkin tällöin neljä akselia (ulottuvuutta), joten meidän ihmisten (ainakin minun) on mahdoton tulkita hajontakuviota! Vaihtoehtoisesti hajontakuviot voi piirtää pareittain kuten kuvassa <a href="moniulotteiset-jakaumat.html#fig:body-pairs">2.1</a>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="moniulotteiset-jakaumat.html#cb1-1" tabindex="-1"></a><span class="fu">pairs</span>(body, <span class="at">lower.panel =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:body-pairs"></span>
<img src="tidaja-book_files/figure-html/body-pairs-1.png" alt="Hajontakuviot muuttujista pareittain." width="672" />
<p class="caption">
Kuva 2.1: Hajontakuviot muuttujista pareittain.
</p>
</div>
<p>Esimerkiksi kuvan <a href="moniulotteiset-jakaumat.html#fig:body-pairs">2.1</a> alareunassa olevassa hajontakuviossa muuttuja <code>TotalHeight</code> on <span class="math inline">\(x\)</span>-akselilla ja muuttuja <code>ArmLength</code> on <span class="math inline">\(y\)</span>-akselilla. Kyseisen hajontakuvion perusteella näyttää, että muuttujien <code>ArmLength</code> ja <code>TotalHeight</code> välillä tosiaan on lineaarinen riippuvuus – keskimäärin pidemmällä ihmisellä on pidemmät kädet. Toki hajontakuviossa näkyy myös muutamia oudokkeja (eng: <em>outlier</em>), jotka ovat poikkeus säännöstä. Huomaa, että pareittaiset hajontakuviot eivät kerro koko tarinaa. Voi nimittäin olla, että tietynlaiset muuttujien väliset riippuvuudet eivät näy hajontakuvioissa.</p>
</div>
<p>Kurssilla käymme läpi perusmenetelmiä, joilla voi tehdä tilastollista analyysiä moniulotteisiin aineistoihin liittyen. Kurssin menetelmät toimivat pohjana vaativimille moniulotteisille data-analyyseille. Moniulotteisen data-analyysin tavoitteena voi esimerkiksi olla</p>
<ul>
<li>Muuttujien riippuvuussuhteiden ymmärtäminen</li>
<li>Yhden muuttujan ennustaminen muilla muuttujilla</li>
<li>Dimensioiden pienennys (eng: <em>dimension reduction</em>) ennen varsinaista analyysiä</li>
</ul>
<p>Kuitenkin ensin täytyy ymmärtää moniulotteiseen dataan liittyvää todennäköisyyslaskentaa, sillä moniulotteista dataa mallinnetaan moniulotteisten satunnaismuuttujien eli satunnaisvektoreiden avulla. Luvussa <a href="moniulotteiset-jakaumat.html#sec:dep">2.1</a> määrittelemme stokastisen riippuvuuden käsitteen formaalisti, jotta voimme ymmärtää satunnaismuuttujien välisiä riippuvuussuhteita. Luvussa <a href="moniulotteiset-jakaumat.html#sec:rvec">2.2</a> määrittelemme satunnaisvektorin, ja siihen liittyvät peruskäsitteet. Luvussa <a href="moniulotteiset-jakaumat.html#sec:cond">2.4</a> syvennämme satunnaisvektoreihin liittyvää todennäköisyysteoriaa käsittelemällä ehdolliset jakaumat. Erittäin tärkeälle jakaumaperheelle eli moniulotteiselle normaalijakaumalle omistetaan oma luku <a href="moniulotteiset-jakaumat.html#sec:normal">2.3</a>. Tärkeimmät moniulotteista jakaumaa kuvaavat teoreettiset suureet kuten odotusarvo ja kovarianssi määritellään luvussa <a href="moniulotteiset-jakaumat.html#sec:statistic">2.5</a>. Samassa luvussa käydään estimoinnin perusteita liittyen moniulotteisiin jakaumiin.</p>
<div id="sec:dep" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Stokastinen riippumattomuus<a href="moniulotteiset-jakaumat.html#sec:dep" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Intuitiivisesti ajateltuna kaksi satunnaismuuttujaa <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat stokastisesti riippumattomia, jos tieto muuttujan <span class="math inline">\(X\)</span> arvosta ei anna mitään lisätietoa muuttujan <span class="math inline">\(Y\)</span> arvosta ja päinvastoin. Toisaalta satunnaismuuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat stokastisesti riippuvia, jos tieto <span class="math inline">\(X\)</span>:n arvosta antaa jotain lisätietoa <span class="math inline">\(Y\)</span>:n arvosta ja päinvastoin.</p>
<div class="example">
<p><span id="exm:ind" class="example"><strong>Esimerkki 2.2  (Riippuvuus intuitiivisesti) </strong></span></p>
<ul>
<li><p>Määritellään satunnaismuuttujat <span class="math inline">\(X = \mathrm{Markkinointi\ (euroissa)}\)</span> ja <span class="math inline">\(Y = \mathrm{Myynti\ (euroissa)}\)</span>. Todennäköisesti edellä annetut satunnaismuuttujat riippuvat toisistaan. Mitä enemmän yritys markkinoi, sitä enemmän myynti kasvaa (ainakin johonkin pisteeseen asti).</p></li>
<li><p>Määritellään satunnaismuuttujat <span class="math inline">\(X = \mathrm{kolikonheiton\ tulos}\)</span> ja <span class="math inline">\(Y = \mathrm{nopanheiton\ tulos}\)</span>. Muuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat riippumattomia, jos kyseessä on aivan tavallinen noppa ja aivan tavallinen kolikko. Jos heitän ensin kolikko ja saan klaavan, niin tämä tulos ei kerro mitään siitä, minkä silmäluvun tulen saamaan heittämällä seuraavaksi noppaa.</p></li>
</ul>
<p>Yllä olevissa esimerkeissä satunnaismuuttujien välinen riippuvuus/riippumattomuus oli helposti pääteltävissä. Aina tilanne ei kuitenkaan ole niin yksinkertainen:</p>
<ul>
<li>Olkoon <span class="math inline">\(X_1\)</span> ja <span class="math inline">\(X_2\)</span> riippumattomia <span class="math inline">\(\pm 1\)</span> arvoisia satunnaismuuttujia niin, että
<span class="math display">\[\begin{equation*}
\mathbb{P}\left(X_i = -1\right) = \mathbb{P}\left(X_i = +1\right)
= \frac{1}{2}, \quad i\in\{1,2\}.
\end{equation*}\]</span>
Määritellään satunnaismuuttuja <span class="math inline">\(Y = X_1 X_2\)</span>. Ovatko satunnaismuuttujat <span class="math inline">\(Y\)</span> ja <span class="math inline">\(X_1\)</span> stokastisesti riippumattomia?
<ul>
<li>Intuitiivisesti ajateltuna muuttujat <span class="math inline">\(Y\)</span> ja <span class="math inline">\(X_1\)</span> eivät välttämättä ole riippumattomia, koska <span class="math inline">\(Y\)</span> määritellään muuttujan <span class="math inline">\(X_1\)</span> avulla. Tästä huolimatta muuttujat <span class="math inline">\(Y\)</span> ja <span class="math inline">\(X_1\)</span> ovat stokastisesti riippumattomia!</li>
</ul></li>
</ul>
</div>
<p>Seuraavaksi annamme stokastisen riippumattomuuden/riippuvuuden määritelmän kahden satunnaismuuttujan välillä.</p>
<div class="definition">
<p><span id="def:ind" class="definition"><strong>Määritelmä 2.1  (Stokastinen riippumattomuus) </strong></span>Satunnaismuuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat riippumattomia, jos kaikille <span class="math inline">\(x\in\mathbb{R}\)</span> ja <span class="math inline">\(y\in\mathbb{R}\)</span> pätee
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X\leq x \cap Y\leq y\right)
  = \mathbb{P}\left(X\leq x\right) \mathbb{P}\left(Y\leq y\right).
\end{equation*}\]</span>
Jos jollekin <span class="math inline">\((x,y)\)</span>-yhdistelmälle pätee
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X\leq x \cap Y\leq y\right)
  \neq \mathbb{P}\left(X\leq x\right) \mathbb{P}\left(Y\leq y\right),
\end{equation*}\]</span>
niin satunnaismuuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat riippuvia.</p>
</div>
<p>Eli satunnaismuuttujat ovat riippumattomia, jos niitä vastaava “yhteistodennäköisyys” voidaan aina kirjoittaa tulomuodossa. Määritelmä <a href="moniulotteiset-jakaumat.html#def:ind">2.1</a> voidaan antaa myös tapahtumien avulla. Muuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> ovat riippumattomia, jos kaikille tapahtumille <span class="math inline">\(\{X\in A\}\)</span> ja <span class="math inline">\(\{Y\in B\}\)</span> pätee
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X\in A \cap Y\in B\right)
  = \mathbb{P}\left(X\in A\right) \mathbb{P}\left(Y\in B\right).
\end{equation*}\]</span>
Toisaalta määritelmä <a href="moniulotteiset-jakaumat.html#def:ind">2.1</a> yleistyy myös useammalle satunnaismuuttujalle. Eli muuttujat <span class="math inline">\(X_1, \ldots, X_n\)</span> ovat riippumattomia, jos kaikille <span class="math inline">\(x_1\in\mathbb{R}, \ldots, x_n\in\mathbb{R}\)</span> pätee
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X_1\leq x_1 \cap \cdots  \cap X_n\leq x_n\right)
  = \mathbb{P}\left(X_1\leq x_1\right) \cdots \mathbb{P}\left(X_n\leq x_n\right).
\end{equation*}\]</span>
Kuten luvussa <a href="moniulotteiset-jakaumat.html#sec:rvec">2.2</a> tullaan näkemään, niin satunnaisvektoreiden käsittely yksinkertaistuu huomattavasti, jos kaikki vektorin muuttujat ovat riippumattomia.</p>
<p>Seuraavaksi annamme esimerkin, jossa tarkistetaan kahden satunnaismuuttujan välinen riippumattomuus/riippuvuus.</p>
<div class="example">
<p><span id="exm:coin" class="example"><strong>Esimerkki 2.3  (Kolikonheitto) </strong></span>Heitetään kolikkoa kolme kertaa. Yhden kolikonheiton tulos on joko klaava (<span class="math inline">\(T\)</span>) tai kruuna (<span class="math inline">\(H\)</span>) js kolikko on reilu eli
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(T\right) = \mathbb{P}\left(H\right) = \frac{1}{2}.
\end{equation*}\]</span>
Kolikonheitot ovat myös toisistaan riippumattomia.</p>
<p>Määritellään kaksi satunnaismuuttujaa:</p>
<ul>
<li><p><span class="math inline">\(X = \text{Klaavojen määrä kahdella ensimmäisellä heitolla}\)</span>.</p></li>
<li><p><span class="math inline">\(Y = \text{Klaavojen määrä kahdella viimeisellä heitolla}\)</span>.</p></li>
</ul>
<p>Tarkoitus on selvittää ovatko muuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> riippumattomia. Tarkastellaan seuraavia tapahtumia:</p>
<ul>
<li><p>Tapahtuma <span class="math inline">\(1\)</span>: <span class="math inline">\(\{X = 0\}\)</span></p></li>
<li><p>Tapahtuma <span class="math inline">\(2\)</span>: <span class="math inline">\(\{Y = 0\}\)</span></p></li>
<li><p>Tapahtuma <span class="math inline">\(3\)</span>: <span class="math inline">\(\{X = 0 \cap Y = 0\}\)</span>.</p></li>
</ul>
<p>Kaikki mahdolliset heittosarjat ovat
<span class="math display">\[\begin{equation*}
  \{\underbrace{(HHH)}_{s_1}, \underbrace{(HHT)}_{s_2},
  \underbrace{(HTH)}_{s_3}, \underbrace{(THH)}_{s_4},
  \underbrace{(TTH)}_{s_5}, \underbrace{(THT)}_{s_6},
  \underbrace{(HTT)}_{s_7}, \underbrace{(TTT)}_{s_8}\}
\end{equation*}\]</span>
Jokaisen heittosarjan <span class="math inline">\(s_i\)</span> todennäköisyys on <span class="math inline">\((1/2)^3 = 1/8\)</span>, koska heitot ovat riippumattomia. Tapahtuma <span class="math inline">\(1\)</span> toteutuu heittosarjoilla <span class="math inline">\(s_1\)</span> ja <span class="math inline">\(s_2\)</span>. Heittosarjat ovat toisensa poissulkevia, joten <span class="math inline">\(\mathbb{P}\left(X = 0\right) = \mathbb{P}\left(s_1 \cup s_2\right) = \mathbb{P}\left(s_1\right) + \mathbb{P}\left(s_2\right) = 1/8 + 1/8 = 1/4\)</span>. Samanlaisella päättelyllä saadaan <span class="math inline">\(\mathbb{P}\left(Y = 0\right) = 1/4\)</span>. Toisaalta tapahtuma 3 toteutuu vain heittosarjalla <span class="math inline">\(s_1\)</span>, joten <span class="math inline">\(\mathbb{P}\left(X = 0 \cap Y = 0\right) = \mathbb{P}\left(s_1\right) = 1/8\)</span>. Saimme siis
<span class="math display">\[\begin{equation*}
\frac{1}{16} =  \left(\frac{1}{4}\right)^2
= \mathbb{P}\left(X = 0\right)\mathbb{P}\left(Y = 0\right)
\neq \mathbb{P}\left(X = 0 \cap Y = 0\right) = \frac{1}{8},
\end{equation*}\]</span>
joten muuttuvat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> <em>eivät</em> ole riippumattomia.</p>
</div>
<p>Lineaarinen riippuvuus on tilastotieteessä erityisen tärkeä riippuvuuden muoto. Kahden satunnaismuuttujan <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> välistä lineaarista riippuvuutta mittaa kovarianssi,
<span class="math display">\[\begin{equation*}
  \mathrm{Cov}\left(X, Y\right) =
  \mathbb{E}\left(\left(X - \mathbb{E}\left(X\right)\right)
  \left(Y - \mathbb{E}\left(Y\right)\right)\right).
\end{equation*}\]</span>
Jos satunnaismuuttujista <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> on otokset <span class="math inline">\(x_1, \ldots, x_n\)</span> ja <span class="math inline">\(y_1, \ldots, y_n\)</span>, niin kovarianssia voidaan estimoida otoskovarianssilla
<span class="math display">\[\begin{equation*}
  s_{XY} = \frac{1}{n - 1}\sum_{i = 1}^n\left(x_i - \bar x\right)
  \left(y_i - \bar y\right),
\end{equation*}\]</span>
jossa <span class="math inline">\(\bar y\)</span> on otosta <span class="math inline">\(y_1, \ldots, y_n\)</span> vastaava keskiarvo. Kovarianssia voidaan tulkita seuraavasti:</p>
<ul>
<li><p>Kun <span class="math inline">\(\mathrm{Cov}\left(X, Y\right) &gt; 0\)</span>, niin muuttujien <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> välillä on kasvava lineaarinen riippuvuus</p></li>
<li><p>Kun <span class="math inline">\(\mathrm{Cov}\left(X, Y\right) &lt; 0\)</span>, niin muuttujien <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> välillä on vähenevä lineaarinen riippuvuus</p></li>
</ul>
<p>Kovarianssin suuruuteen vaikuttaan muuttujien <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> skaalat, joten kovarianssin suuruutta <span class="math inline">\(\left|\mathrm{Cov}\left(X, Y\right)\right|\)</span> on vaikea tulkita. Tämän vuoksi kovarianssi usein normalisoidaan jakamalla satunnaismuuttujia vastaavilla keskihajonnoilla, jolloin päädytään (Pearsonin) korrelaatiokertoimeen,
<span class="math display">\[\begin{equation*}
  \mathrm{Cor}\left(X, Y\right) = \frac{\mathrm{Cov}\left(X, Y\right)}
  {\sqrt{\mathrm{Var}\left(X\right)\mathrm{Var}\left(Y\right)}}.
\end{equation*}\]</span>
Korrelaatiokertoimen estimaattori on
<span class="math display">\[\begin{equation*}
  \hat\rho_{XY} = \frac{s_{XY}}{\sqrt{s_X^2s_Y^2}},
\end{equation*}\]</span>
jossa <span class="math inline">\(s_Y^2\)</span> on otosta <span class="math inline">\(y_1, \ldots, y_n\)</span> vastaava otosvarianssi. Korrelaation <span class="math inline">\(\mathrm{Cor}\left(X, Y\right)\)</span> arvo on aina välillä <span class="math inline">\([-1, 1].\)</span> Kuten kovarianssin tapauksessa, korrelaation merkki kertoo siitä, onko lineaarinen riippuvuus kasvava vai vähenevä ja korrelaation suuruus <span class="math inline">\(\left|\mathrm{Cor}\left(X, Y\right)\right|\)</span> kertoo lineaarisen riippuvuuden vahvuudesta. On mahdollista, että satunnaismuuttujat <em>eivät</em> ole riippumattomia ja <span class="math inline">\(\mathrm{Cov}\left(X, Y\right) = 0\)</span>. Esimerkiksi satunnaismuuttujien välillä voi epälineaarinen suhde, kuten kuvan <a href="moniulotteiset-jakaumat.html#fig:cor">2.2</a> oikean alalaidan havaintoaineistossa, jolloin otoskorrelaatio on likimain nolla. Ilmiöön liittyen on myös harjoitustehtävä.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-1" class="exercise"><strong>Tehtävä 2.1  (Viikko 2, tehtävä 2) </strong></span>Olkoon <span class="math inline">\(X\sim \mathrm{Tas}\left([-1,1]\right)\)</span> eli <span class="math inline">\(X\)</span> on satunnaismuuttuja, joka noudattaa tasajakaumaa välillä <span class="math inline">\([-1, 1]\)</span>. Määritellään toinen satunnaismuuttuja muunnoksen <span class="math inline">\(Y = X^2\)</span> mukaan. Tällöin satunnaismuuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> <em>eivät</em> ole riippumattomia mutta <span class="math inline">\(\mathrm{Cov}\left(X, Y\right) = 0\)</span>.</p>
</div>

<div class="figure"><span style="display:block;" id="fig:cor"></span>
<img src="images/correlation.jpg" alt="Otoskorrelaation \(\hat\rho_{XY}\) suuruusluokka erilaisille havaintoaineistoille." width="858" />
<p class="caption">
Kuva 2.2: Otoskorrelaation <span class="math inline">\(\hat\rho_{XY}\)</span> suuruusluokka erilaisille havaintoaineistoille.
</p>
</div>
<div class="remark">
<p><span id="unlabeled-div-2" class="remark"><em>Huomautus</em>. </span>Vapaaehtoisena lisätehtävänä voit määritelmän <a href="moniulotteiset-jakaumat.html#def:ind">2.1</a> avulla tarkistaa, että esimerkin <a href="moniulotteiset-jakaumat.html#exm:ind">2.2</a> viimeinen väite pätee.</p>
</div>
</div>
<div id="sec:rvec" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Perusteet<a href="moniulotteiset-jakaumat.html#sec:rvec" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Moniulotteisia satunnaismuuttujia mallinnetaan satunnaisvektoreina, joten kerrataan vektorin käsite. Vektori (<span class="math inline">\(d\)</span>-ulotteinen) on <strong>järjestetty</strong> lista lukuja <span class="math inline">\((x_1, x_2, \ldots, x_d)\)</span>, <span class="math inline">\(x_i\in\mathbb{R}\)</span>. Eli vektori voidaan tulkita avaruuden <span class="math inline">\(\mathbb{R}^d\)</span> alkiona. Esimerkiksi <span class="math inline">\(2\)</span>-ulotteiset vektorit voidaan piirtää pisteinä tai paikkavektoreina (nuoli lähtien nollasta päättyen vektorin määräämiin koordinaatteihin) tasossa <span class="math inline">\(\mathbb{R}^2\)</span> kuten kuvassa <a href="moniulotteiset-jakaumat.html#fig:vec">2.3</a>. Samoin <span class="math inline">\(d\)</span>-ulotteiset vektorit voidaan tulkita pisteinä avaruudessa <span class="math inline">\(\mathbb{R}^d\)</span> mutta visualisointi muuttuu mahdottomaksi kun <span class="math inline">\(d &gt; 3\)</span>. Korostamme vielä, että vektorien alkioiden järjestyksellä on väliä eli esimerkiksi <span class="math inline">\((1, 2) \neq (2, 1)\)</span>.</p>
<div class="remark">
<p><span id="unlabeled-div-3" class="remark"><em>Huomautus</em> (Vektorinotaatioista). </span></p>
<ul>
<li><p>Joskus vektorit erotetaan luvuista lihavoimalla vektorit. Tässä monisteessa käytämme kyseistä periaatetta eli <span class="math inline">\(\boldsymbol x\)</span> tulkitaan vektorina ja <span class="math inline">\(x\)</span> lukuna.</p></li>
<li><p>Usein oletuksena vektorit tulkitaan pystyvektoreina. Sillä onko <span class="math inline">\(\boldsymbol x\)</span> pysty- vai vaakavektori on merkitystä vektoreiden välisissä laskutoimituksissa. Muista, että notaatio <span class="math inline">\(\boldsymbol x^T\)</span> tarkoittaa transpoosia, joka muuttaa vaakavektorin pystyvektoriksi ja toisinpäin. Eli esimerkiksi <span class="math inline">\((1, 4, 2.4)^T\)</span> on <span class="math inline">\(3\)</span>-ulotteinen pystyvektori
<span class="math display">\[\begin{equation*}
\begin{pmatrix}
1 \\ 4 \\ 2.4
\end{pmatrix},
\end{equation*}\]</span>
joten monisteessa merkitsemme pystyvektoreita esimerkiksi notaatiolla <span class="math inline">\(\boldsymbol y = (4, 1, 8, 2)^T\)</span>.</p></li>
</ul>
</div>
<p>Vektorin <span class="math inline">\(\boldsymbol x = (x_1, x_2, \cdots, x_d)\in\mathbb{R}^d\)</span> suuruutta tai pituutta voidaan mitata sen normin <span class="math inline">\(\|\boldsymbol x\|\)</span> avulla,
<span class="math display">\[\begin{equation*}
  \|\boldsymbol x\| = \sqrt{\sum_{i = 1}^d x_i^2}.
\end{equation*}\]</span>
Suuruuden lisäksi vektorilla on suunta. Työkalu vektorin suunnan määrittämiseen on pistetulo. Kahden vektorin <span class="math inline">\(\boldsymbol x\in\mathbb{R}^d\)</span> ja <span class="math inline">\(\boldsymbol y\in\mathbb{R}^d\)</span> välinen pistetulo määritellään seuraavasti,
<span class="math display">\[\begin{equation*}
  \langle \boldsymbol x, \boldsymbol y\rangle = \sum_{i = 1}^d x_i y_i.
\end{equation*}\]</span>
Erityisesti kaksi vektoria <span class="math inline">\(\boldsymbol x\)</span> ja <span class="math inline">\(\boldsymbol y\)</span> ovat suorassa kulmassa toisiinsa nähden jos ja vain jos <span class="math inline">\(\langle \boldsymbol x, \boldsymbol y\rangle = 0\)</span>.</p>
<div class="example">
<p><span id="exm:unlabeled-div-4" class="example"><strong>Esimerkki 2.4  (Vektorin suuruus ja suunta) </strong></span></p>
<ul>
<li><p>Kuvan <a href="moniulotteiset-jakaumat.html#fig:vec">2.3</a> vektoreilla <span class="math inline">\((2,2)^T\)</span> ja <span class="math inline">\((-1, \sqrt{7})^T\)</span> on sama normi.</p></li>
<li><p>Kuvan <a href="moniulotteiset-jakaumat.html#fig:vec">2.3</a> vektoreiden <span class="math inline">\((2, 2)^T\)</span> ja <span class="math inline">\((-1, 1)^T\)</span> välinen pistetulo on nolla.</p></li>
</ul>
</div>

<div class="figure"><span style="display:block;" id="fig:vec"></span>
<img src="images/vectors.jpg" alt="Vektoreita karteesisessa koordinaatistossa." width="730" />
<p class="caption">
Kuva 2.3: Vektoreita karteesisessa koordinaatistossa.
</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-5" class="example"><strong>Esimerkki 2.5  (Havaintoaineisto ja vektorit) </strong></span></p>
<ul>
<li>Esimerkin <a href="moniulotteiset-jakaumat.html#exm:body">2.1</a> aineiston havainnot (rivit) voidaan tulkita <span class="math inline">\(4\)</span>-ulotteisina vektoreina eli pisteinä avaruudessa <span class="math inline">\(\mathbb{R}^4\)</span>.</li>
</ul>
</div>
<p>Nyt olemme valmiita määrittelemään satunnaisvektorit.</p>
<div class="definition">
<p><span id="def:rvec" class="definition"><strong>Määritelmä 2.2  (Satunnaisvektori ja sen yhteiskertymäfunktio) </strong></span>Olkoon <span class="math inline">\(X_1, X_2, \ldots, X_d\)</span> satunnaismuuttujia. Tällöin <span class="math inline">\(\boldsymbol X = (X_1, X_2, \ldots, X_d)^T\)</span> on <span class="math inline">\(d\)</span>-ulotteinen satunnaisvektori. Satunnaisvektorin yhteiskertymäfunktio <span class="math inline">\(F_{\boldsymbol X}(\boldsymbol x):\mathbb{R}^d\to[0,1]\)</span> kohdassa <span class="math inline">\(\boldsymbol x = (x_1, x_2, \ldots, x_d)\)</span> määritellään seuraavasti,
<span class="math display">\[\begin{equation*}
  \begin{split}
    F_{\boldsymbol X}(\boldsymbol x)
    = \mathbb{P}\left(X_1\leq x_1, X_2\leq x_2, \ldots, X_d\leq x_d\right),
  \end{split}
\end{equation*}\]</span>
jolle voidaan käyttää myös tiiviimpää notaatiota <span class="math inline">\(F_{\boldsymbol X}(\boldsymbol x) = \mathbb{P}\left(\boldsymbol X \leq \boldsymbol x\right)\)</span>.</p>
</div>
<p>Yksiulotteisen satunnaismuuttujan <span class="math inline">\(X\)</span> tapauksessa kertymäfunktio <span class="math inline">\(F_X(x), x\in\mathbb{R}\)</span> antaa kaiken informaation kyseisen satunnaismuuttujan jakaumasta <span class="math inline">\(\mathbb{P}\left(X\in A\right), A\subset\mathbb{R}\)</span>. Samoin moniulotteisen satunnaisvektorin tapauksessa yhteiskertymäfunktio <span class="math inline">\(F_{\boldsymbol X}(\boldsymbol x)\)</span> antaa kaiken informaation kyseisen satunnaisvektorin jakaumasta <span class="math inline">\(\mathbb{P}\left(\boldsymbol X\in B\right), B\subset\mathbb{R}^d\)</span>. Sanomme siis, että kaksi satunnaisvektoria <span class="math inline">\(\boldsymbol X\)</span> ja <span class="math inline">\(\boldsymbol Y\)</span> ovat samoin jakautuneet, jos <span class="math inline">\(F_{\boldsymbol X}(\boldsymbol x) = F_{\boldsymbol Y}(\boldsymbol x)\)</span> pätee kaikille <span class="math inline">\(\boldsymbol x\in\mathbb{R}^d\)</span>.</p>
<p>Huomautamme jo tässä kohtaa, että usein informaatio yksittäisistä komponenttimuuttujista <span class="math inline">\(X_1, \ldots, X_d\)</span> kertoo varsin vähän satunnaisvektorista <span class="math inline">\(\boldsymbol X = (X_1, \ldots, X_d)\)</span> – yleisesti ottaen satunnaismuuttujien <span class="math inline">\(X_i\)</span> kertymäfunktioista <span class="math inline">\(F_{X_i}\)</span> <strong>ei</strong> voida päätellä satunnaisvektorin <span class="math inline">\(\boldsymbol X\)</span> yhteiskertymäfunktiota <span class="math inline">\(F_{\boldsymbol X}\)</span>. Sääntöön löytyy kuitenkin yksi poikkeus.</p>
<div class="theorem">
<p><span id="thm:unlabeled-div-6" class="theorem"><strong>Fakta 2.1  (Riippumattomat komponenttivektorit) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2, \ldots, X_d)\)</span> satunnaisvektori niin, että satunnaismuuttujat <span class="math inline">\(X_1, X_2, \ldots, X_d\)</span> ovat riippumattomia. Tällöin riippumattomuuden määritelmästä seuraa, että kohdassa <span class="math inline">\(\boldsymbol x = (x_1, x_2,\ldots, x_d)\)</span> satunnaisvektorin <span class="math inline">\(\boldsymbol X\)</span> kertymäfunktio voidaan kirjoittaa muodossa
<span class="math display">\[\begin{equation*}
  F_{\boldsymbol X}(\boldsymbol x) = F_{X_1}(x_1)F_{X_2}(x_2)\cdots F_{X_d}(x_d)
  = \prod_{i = 1}^d F_{X_1}(x_i).
\end{equation*}\]</span>
Eli satunnaisvektoria vastaava yhteiskertymäfunktio <span class="math inline">\(F_{\boldsymbol X}(\boldsymbol x)\)</span> on tulo komponenttimuuttujien <span class="math inline">\(X_i\)</span> kertymäfunktioista <span class="math inline">\(F_{X_i}(x_i)\)</span>.</p>
</div>
<div class="remark">
<p><span id="unlabeled-div-7" class="remark"><em>Huomautus</em>. </span>Yllä puhumme satunnaisvektorin <span class="math inline">\(\boldsymbol X\)</span> <em>yhteis</em>jakaumasta, <em>yhteis</em>kertymäfunktiosta jne. Tästä eteenpäin tiputamme etuliitteen “yhteis”, kun on selkeää mistä puhutaan.</p>
</div>
<p>Seuraavaksi käsittelemme konkreettisempia esimerkkejä satunnaisvektoreista. Aloitamme diskreeteistä moniulotteisista satunnaismuuttujista, minkä jälkeen sanomme muutaman sanan jatkuvista moniulotteisista satunnaismuuttujista.</p>
<div id="diskreetti-satunnaisvektori" class="section level3 unnumbered hasAnchor">
<h3>Diskreetti satunnaisvektori<a href="moniulotteiset-jakaumat.html#diskreetti-satunnaisvektori" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Diskreetit satunnaisvektorit tarjoavat todennäköisyysteoreettisen mallin monille yksinkertaisille sekä monimutkaisille moniulotteisille ilmiölle:</p>
<ul>
<li><p>Peräkkäiset kolikonheitot</p></li>
<li><p>Jonotusmallit</p>
<ul>
<li>esim. asiakkaiden määrät useammassa jonossa</li>
</ul></li>
<li><p>Luonnollisen kielen prosessointi (eng: <em>natural language processing</em>)</p>
<ul>
<li>esim. tilastollinen malli (tai teköälymalli) saattaa ottaa sisäänsä vektoreita, joiden alkiot kuvaavat sanojen lukumääriä dokumentissa (eng: <em>bag-of-words model</em>)</li>
</ul></li>
</ul>
<div class="definition">
<p><span id="def:discrete" class="definition"><strong>Määritelmä 2.3  (Diskreetti satunnaisvektori) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2, \ldots, X_d)^T\)</span> satunnaisvektori. Satunnaisvektori <span class="math inline">\(\boldsymbol X\)</span> on diskreetti, jos sen arvojoukko on <span class="math inline">\(\mathbb{Z}^d\)</span> eli <span class="math inline">\(X_i\in\mathbb{Z}\)</span> kaikilla <span class="math inline">\(i\)</span>. Diskreetin satunnaisvektorin <span class="math inline">\(\boldsymbol X\)</span> yhteispistetodennäköisyysfunktio <span class="math inline">\(p_{\boldsymbol X}:\mathbb{Z}^d\to[0,1]\)</span> määritellään kaavan
<span class="math display">\[\begin{equation*}
  p_{\boldsymbol X}(x_1, x_2,\ldots, x_d)
  = \mathbb{P}\left(X_1 = x_1, X_2 = x_2, \ldots, X_d = x_d\right)
\end{equation*}\]</span>
mukaan.</p>
</div>
<p>Alla on pari esimerkkiä diskreeteistä satunnaisvektoreista. Huomaa, että diskreetin satunnaisvektorin arvojoukko ei tarvitse olla <span class="math inline">\(\mathbb{Z} = \{\ldots,-2, -1, 0, 1, 2,\ldots\}\)</span> kokonaisuudessaan vaan se voi olla myös joukon <span class="math inline">\(\mathbb{Z}\)</span> osajoukko.</p>
<div class="example">
<p><span id="exm:unlabeled-div-8" class="example"><strong>Esimerkki 2.6  (Diskreetti satunnaisvektori) </strong></span></p>
<ul>
<li><p>Olkoon <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> kuten esimerkissä <a href="moniulotteiset-jakaumat.html#exm:coin">2.3</a>. Tällöin <span class="math inline">\((X, Y)^T\)</span> on <span class="math inline">\(2\)</span>-ulotteinen diskreetti satunnaisvektori, jonka arvojoukko on
<span class="math display">\[\begin{equation*}
\{(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)\}
\subset \mathbb{Z}.
\end{equation*}\]</span></p></li>
<li><p>Heitetään noppaa viisi kertaa peräkkäin (<span class="math inline">\(X_i = \mathrm{Heiton}\ i\ \mathrm{tulos}\)</span>, <span class="math inline">\(i\in\{1,2,3,4,5\}\)</span>). Tällöin <span class="math inline">\((X_1, X_2, X_3, X_4, X_5)^T\)</span> on <span class="math inline">\(5\)</span>-ulotteinen diskreetti satunnaisvektori, jonka arvojoukko on <span class="math inline">\(\{(j_1, j_2, j_3, j_4, j_5) : j_i\in\{1,2,3,4,5,6\}\}\)</span>.</p></li>
</ul>
</div>
<p>Määritelmässä <a href="moniulotteiset-jakaumat.html#def:discrete">2.3</a> annettu pistetodennäköisyysfunktio on tärkeä työkalu diskreetin satunnaisvektorin jakauman tutkimisessa. Alla annamme pistetodennäköisyysfunktion ominaisuudet (epänegatiivisuus ja summautuminen ykköseen). Huomaa myös että jos joku mielivaltainen funktio <span class="math inline">\(g\)</span> toteuttaa pistetodennäköisyysfunktion ehdot, niin <span class="math inline">\(g = g_{\boldsymbol Y}\)</span> tosiaan on jonkin satunnaisvektorin <span class="math inline">\(\boldsymbol Y\)</span> pistetodennäköisyysfunktio.</p>
<div class="theorem">
<p><span id="thm:pointmass" class="theorem"><strong>Fakta 2.2  (Pistetodennäköisyysfunktion ominaisuudet) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2, \ldots, X_d)^T\)</span> diskreetti satunnaisvektori, jolla on pistetodennäköisyysfunktio <span class="math inline">\(p_{\boldsymbol X}\)</span>.
Pistetodennäköisyysfunktio <span class="math inline">\(p_{\boldsymbol X}\)</span> toteuttaa seuraavat ehdot:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(p_{\boldsymbol X}(x_1, x_2,\ldots, x_d) \geq 0\)</span> kaikille vektoreille <span class="math inline">\((x_1, x_2, \ldots, x_d)\in\mathbb{Z}^d\)</span> (epänegatiivisuus)</p></li>
<li><p><span class="math inline">\(\sum_{x_1, x_2, \ldots, x_d} p_{\boldsymbol X}(x_1, x_2,\ldots, x_d) = \sum_{x_1\in\mathbb{Z}}\sum_{x_2\in\mathbb{Z}} \cdots \sum_{x_d\in\mathbb{Z}} p_{\boldsymbol X}(x_1, x_2,\ldots, x_d) = 1\)</span> (summautuu ykköseen)</p></li>
</ol>
<p>Vastaavasti, jos joku mielivaltainen funktio <span class="math inline">\(g:\mathbb{Z}^d\to[0,1]\)</span> toteuttaa ehdot 1 ja 2, niin se on jonkin diskreetin satunnaisvektorin pistetodennäköisyysfunktio.</p>
</div>
<p>Alla on esimerkki pistetodennäköisyysfunktion ehtojen 1 ja 2 tarkistamisesta.</p>
<div class="example">
<p><span id="exm:unlabeled-div-9" class="example"><strong>Esimerkki 2.7  (Pistetodennäköisyysfunktion ehdot) </strong></span>Olkoon <span class="math inline">\(C &gt; 0\)</span> ja määritellään funktio <span class="math inline">\(f:\mathbb{Z^2}\to \mathbb{R}\)</span> kaavalla
<span class="math display">\[\begin{equation*}
  f(x,y) =
  \begin{cases}
    \frac{1}{5}C, &amp; x = 1, y = 1, \\
    \frac{1}{3}C, &amp; x = 1, y = 2, \\
    \frac{2}{5}C, &amp; x = 2, y = 1, \\
    \frac{1}{2}C, &amp; x = 2, y = 2, \\
    0, &amp; \text{muulloin}.
  \end{cases}
\end{equation*}\]</span>
Määritetään vakio <span class="math inline">\(C\)</span> siten, että <span class="math inline">\(f\)</span> on diskreetin satunnaisvektorin pistetodennäköisyysfunktio. Eli vakio <span class="math inline">\(C\)</span> tulee valita niin, että faktan <a href="moniulotteiset-jakaumat.html#thm:pointmass">2.2</a> ehdot 1 ja 2 täyttyvät. Kunhan <span class="math inline">\(C \geq 0\)</span>, niin ehto 1 täyttyy selvästi. Tarkistetaan siis ehto 2. Sievennetään ensin summa <span class="math inline">\(\sum_{x,y} f(x,y)\)</span>,
<span class="math display">\[\begin{equation*}
  \begin{split}
    \sum_{x\in\mathbb{Z}}\sum_{y\in\mathbb{Z}} f(x,y)
    &amp;= \sum_{x\in\{1, 2\}}\sum_{y\in\{1, 2\}} f(x,y) \\
    &amp;= \sum_{x\in\{1, 2\}} f(x, 1) + f(x, 2) \\
    &amp;= f(1,1) + f(1,2) + f(2,1) + f(2,2) \\
    &amp;= C\left(\frac{1}{5} + \frac{1}{3} + \frac{2}{5} + \frac{1}{2}\right) \\
    &amp;= \frac{43}{30} C.
  \end{split}
\end{equation*}\]</span>
Ehdon 2 yhtälö <span class="math inline">\(\sum_{x,y} f(x,y) = 1\)</span> voidaan siis kirjoittaa muodossa <span class="math inline">\(\frac{43}{30} C = 1\)</span>, josta saadaan <span class="math inline">\(C = \frac{30}{43}\)</span>.</p>
<p>Tämä pistetodennäköisyysfunktio sopisi vaikka kuvaamaan yrityksen yksinkertaistettua asiakastyytyväisyyskartoituksen tulosta, jossa ensimmäinen komponenttimuuttuja <span class="math inline">\(X\)</span> kuvaa asiakkaan tekemien ostotapahtumien yleisyyttä (harvoin / usein) ja toinen komponenttimuuttuja <span class="math inline">\(Y\)</span> kuvaa
asiakastyytyväisyyttä (tyytymätön / tyytyväinen). Nyt voimme esimerkiksi laskea
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X = 1, Y = 2\right) = f(1,2)
  = \frac{1}{3}\cdot \frac{30}{43} \approx 0.23.
\end{equation*}\]</span></p>
</div>
<div class="remark">
<p><span id="unlabeled-div-10" class="remark"><em>Huomautus</em>. </span>Huomaa, että esimerkiksi notaatiolla <span class="math inline">\(\mathbb{P}\left(X = i, Y = j, Z = k\right)\)</span> tarkoitamme todennäköisyyttä <span class="math inline">\(\mathbb{P}\left(X = i\ \text{ja}\ Y = j\ \text{ja}\ Z = k\right)\)</span>.</p>
</div>
<p>Seuraavaksi jatkamme esimerkkiä <a href="moniulotteiset-jakaumat.html#exm:coin">2.3</a>. Kyseisen esimerkin tapauksessa määritämme satunnaisvektorin pistetodennäköisyysfunktion.</p>
<div class="example">
<p><span id="exm:coincont" class="example"><strong>Esimerkki 2.8  (Pistetodennäköisyysfunktion määrittäminen) </strong></span>Oletetaan sama asetelma kuin esimerkissä <a href="moniulotteiset-jakaumat.html#exm:coin">2.3</a>. Tarkoitus on nyt määrittää satunnaisvektorin <span class="math inline">\((X,Y)^T\)</span> yhteisjakauma kun satunnaismuuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> määriteltiin seuraavasti:</p>
<ul>
<li><p><span class="math inline">\(X = \mathrm{Klaavojen\ määrä\ kahdella\ ensimmäisellä\ heitolla}\)</span> ja</p></li>
<li><p><span class="math inline">\(Y = \mathrm{Klaavojen\ määrä\ kahdella\ viimeisellä\ heitolla}\)</span>.</p></li>
</ul>
<p>Muistakaamme, että kaikki mahdolliset kolmen kolikonheiton (<span class="math inline">\(T = \text{klaava}\)</span> ja <span class="math inline">\(H = \text{kruuna}\)</span>) sarjat ovat
<span class="math display">\[\begin{equation*}
  \{\underbrace{(HHH)}_{s_1}, \underbrace{(HHT)}_{s_2},
  \underbrace{(HTH)}_{s_3}, \underbrace{(THH)}_{s_4},
  \underbrace{(TTH)}_{s_5}, \underbrace{(THT)}_{s_6},
  \underbrace{(HTT)}_{s_7}, \underbrace{(TTT)}_{s_8}\}
\end{equation*}\]</span>
ja että jokaisen sarjan <span class="math inline">\(s_i\)</span> todennäköisyys on <span class="math inline">\(1/8\)</span>. Nähdään, että jos esimerkiksi <span class="math inline">\(X = 2\)</span>, niin silloin <span class="math inline">\(Y\in\{1,2\}\)</span> (ainakin 1 klaava viimeisen kahden heiton aikana). Esimerkiksi jos <span class="math inline">\(s_8\)</span> tapahtuu, niin tällöin
<span class="math inline">\(X = Y = 2\)</span>. Toisaalta jos <span class="math inline">\(s_5\)</span> tapahtuu, niin <span class="math inline">\(X = 2\)</span> ja <span class="math inline">\(Y = 1\)</span>. Siten
satunnaisvektorin <span class="math inline">\(\boldsymbol Z = (X, Y)^T\)</span> saamat kaikki mahdolliset arvot ovat
<span class="math display">\[\begin{equation*}
  (0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)
\end{equation*}\]</span>
ja tällöin pistetodennäköisyysfunktion <span class="math inline">\(p_{\boldsymbol Z}(x,y) = \mathbb{P}\left(X = x, Y = y\right)\)</span> saamat arvot ovat
<span class="math display">\[\begin{align*}
    p_{\boldsymbol Z}(0,0) &amp;= 1/8,&amp; p_{\boldsymbol Z}(0,1) &amp;= 1/8,&amp; p_{\boldsymbol Z}(0,2) &amp;= 0,&amp; p_{\boldsymbol Z}(1,0) &amp;= 1/8,
    &amp; p_{\boldsymbol Z}(1,1) = 1/4 \\
    p_{\boldsymbol Z}(1,2) &amp;= 1/8,&amp; p_{\boldsymbol Z}(2,0) &amp;= 0,&amp; p_{\boldsymbol Z}(2,1) &amp;= 1/8,&amp; p_{\boldsymbol Z}(2,2) &amp;= 1/8.
\end{align*}\]</span></p>
<p>Pistetodennäköisyysfunktion arvot voidaan myös taulukoida kuten taulukossa <a href="moniulotteiset-jakaumat.html#tab:coinxy">2.2</a>.</p>
<table>
<caption><span id="tab:coinxy">Taulukko 2.2: </span>Pistetodennäköisyysfunktion <span class="math inline">\(p_{\boldsymbol Z}\)</span> arvot taulukoituna.</caption>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(X\)</span></th>
<th align="left"><span class="math inline">\(Y = 0\)</span></th>
<th align="left"><span class="math inline">\(Y = 1\)</span></th>
<th align="left"><span class="math inline">\(Y = 2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(0\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
<td align="left"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(1\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
<td align="left"><span class="math inline">\(1/4\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(2\)</span></td>
<td align="left"><span class="math inline">\(0\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
<td align="left"><span class="math inline">\(1/8\)</span></td>
</tr>
</tbody>
</table>
<p>Yksittäisten satunnaismuuttujien <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> pistetodennäköisyysfunktiot <span class="math inline">\(p_{X}(x) = \mathbb{P}\left(X = x\right)\)</span> ja <span class="math inline">\(p_{X}(x) = \mathbb{P}\left(X = x\right)\)</span> saadaan myös pääteltyä heittosarjojen <span class="math inline">\(s_1, \ldots, s_8\)</span> avulla. Esimerkiksi <span class="math inline">\(X = 1\)</span> heittosarjojen <span class="math inline">\(s_3\)</span>, <span class="math inline">\(s_4\)</span>, <span class="math inline">\(s_6\)</span> ja <span class="math inline">\(s_7\)</span> toteutuessa eli <span class="math inline">\(p_{X}(1) = 1/8 + 1/8 + 1/8 + 1/8 = 1/4\)</span>. Samalla päättelyketjulla saadaan
<span class="math display">\[\begin{equation*}
  p_{X}(0) = p_{Y}(0) = 1/4,\quad p_{X}(1) = p_{Y}(1) = 1/2,\quad p_{X}(2) = p_{Y}(2) = 1/4.
\end{equation*}\]</span>
Myös yksittäisten satunnaismuuttujien pistetodennäköisyysfunktiot voidaan taulukoida. Taulukossa <a href="moniulotteiset-jakaumat.html#tab:coinx">2.3</a> näkyy muuttujan <span class="math inline">\(X\)</span> pistetodennäköisyysfunktion arvot.</p>
<table>
<caption><span id="tab:coinx">Taulukko 2.3: </span>Pistetodennäköisyysfunktion <span class="math inline">\(p_{X}\)</span> arvot taulukoituna. Muuttujaa <span class="math inline">\(Y\)</span> vastaava taulukko näyttää täysin samanlaiselta.</caption>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(X = 0\)</span></th>
<th align="left"><span class="math inline">\(X = 1\)</span></th>
<th align="left"><span class="math inline">\(X = 2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(1/4\)</span></td>
<td align="left"><span class="math inline">\(1/2\)</span></td>
<td align="left"><span class="math inline">\(1/4\)</span></td>
</tr>
</tbody>
</table>
<p>Koska muuttujat <span class="math inline">\(X\)</span> ja <span class="math inline">\(Y\)</span> <strong>eivät</strong> ole riippumattomia, niin pistetodennäköisyysfunktiosta <span class="math inline">\(p_{X}\)</span> ja <span class="math inline">\(p_{Y}\)</span> ei voi päätellä pistetodennäköisyysfunktion <span class="math inline">\(p_{\boldsymbol Z}\)</span> arvoa.</p>
</div>
<p>Kuten yksiulotteisten diskreettien satunnaismuuttujien tapauksessa, myös diskreettien satunnaisvektorien kertymäfunktio (ja jakauma) saadaan pistetodennäköisyysfunktion avulla.</p>
<div class="theorem">
<p><span id="thm:discretecdf" class="theorem"><strong>Fakta 2.3  (Pistetodennäköisyys- ja kertymäfunktion yhteys) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2, \ldots, X_d)^T\)</span> satunnaisvektori, jolla on pistetodennäköisyysfunktio <span class="math inline">\(p_{\boldsymbol X}\)</span>. Pistetodennäköisyys- ja kertymäfunktiolla on seuraava yhteys. Kaikille <span class="math inline">\(\boldsymbol x = (x_1, x_2, \ldots, x_d)\in\mathbb{R}^d\)</span> pätee
<span class="math display" id="eq:discrete-multi-cdf">\[\begin{equation}
  \begin{split}
    F_{\boldsymbol X}\left(\boldsymbol x\right)
    &amp;:= \mathbb{P}\left(X_1\leq x_1, X_2\leq x_2, \ldots, X_d\leq x_d\right) \\
    &amp;= \sum_{u_1\leq x_1} \sum_{u_2\leq x_2} \cdots \sum_{u_d\leq x_d}
    p_{\boldsymbol X}(x_1, x_2,\ldots, x_d).
  \end{split}
  \tag{2.3}
\end{equation}\]</span></p>
</div>
<p>Kaava <a href="moniulotteiset-jakaumat.html#eq:discrete-multi-cdf">(2.3)</a> näyttää siis hyvin samankaltaiselta kuin <a href="moniulotteiset-jakaumat.html#eq:discrete-uni-cdf">(2.1)</a> – yhden summan sijasta on <span class="math inline">\(d\)</span> summaa.</p>
<div class="example">
<p><span id="exm:unlabeled-div-11" class="example"><strong>Esimerkki 2.9  (Pistetodennäköisyysfunktiosta kertymäfunktioon) </strong></span>Vakuutusyritys tarjoaa asiakkailleen sekä ajoneuvo- että kotivakuutusta. Molemmille vakuutustyypeille asiakkaan tulee valita omavastuu. Ajoneuvovakuutuksen omavastuu on joko <span class="math inline">\(100\)</span> tai <span class="math inline">\(250\)</span> euroa. Kotivakuutuksen omavastuu on joko <span class="math inline">\(0\)</span>, <span class="math inline">\(100\)</span> tai <span class="math inline">\(200\)</span> euroa. Valitaan asiakas umpimähkään, ja merkitään</p>
<ul>
<li><p><span class="math inline">\(X_1 = \mathrm{asiakkaan\ omavastuun\ määrä\ autovakuutuksessa}\)</span>,</p></li>
<li><p><span class="math inline">\(X_2 = \mathrm{asiakkaan\ omavastuun\ määrä\ kotivakuutuksessa}\)</span>,</p></li>
</ul>
<p>ja tarkastellaan näiden yhteisjakaumaa eli satunnaisvektoria <span class="math inline">\(\boldsymbol X = (X_1,  X_2)^T\)</span>. Taulukossa <a href="moniulotteiset-jakaumat.html#tab:insurance">2.4</a> näkyy satunnaismuuttujan <span class="math inline">\(\boldsymbol X\)</span> pistetodennäköisyysfunktio taulukoituna.</p>
<table>
<caption><span id="tab:insurance">Taulukko 2.4: </span>Pistetodennäköisyysfunktion <span class="math inline">\(p_{\boldsymbol X}\)</span> arvot taulukoituna.</caption>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(X_1\)</span></th>
<th align="left"><span class="math inline">\(X_2 = 0\)</span></th>
<th align="left"><span class="math inline">\(X_2 = 100\)</span></th>
<th align="left"><span class="math inline">\(X_2 = 200\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(100\)</span></td>
<td align="left"><span class="math inline">\(0.20\)</span></td>
<td align="left"><span class="math inline">\(0.10\)</span></td>
<td align="left"><span class="math inline">\(0.20\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(250\)</span></td>
<td align="left"><span class="math inline">\(0.05\)</span></td>
<td align="left"><span class="math inline">\(0.15\)</span></td>
<td align="left"><span class="math inline">\(0.30\)</span></td>
</tr>
</tbody>
</table>
<p>Todennäköisyys, että satunnaisesti valitun asiakkaan autovakuutuksen omavastuun määrä on <span class="math inline">\(250\)</span> euroa ja kotivakuutuksen omavastuun määrä on <span class="math inline">\(100\)</span> euroa, on
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X_1 = 250, X_2 = 100\right) = 0.15.
\end{equation*}\]</span>
Todennäköisyys, että satunnaisesti valitulla asiakkaalla on autovakuutuksen omavastuu <span class="math inline">\(250\)</span> euroa tai vähemmän, ja kotivakuutuksen omavastuu
<span class="math inline">\(100\)</span> euroa tai vähemmän on
<span class="math display">\[\begin{equation*}
  \begin{split}
    \mathbb{P}\left(X_1\leq 250, X_2\leq 100\right)
    &amp;= \sum_{u_1\leq 250} \sum_{u_2\leq 100} p_{\boldsymbol X}\left(u_1, u_2\right) \\
    &amp;= \sum_{u_1\leq 250} p_{\boldsymbol X}\left(u_1, 0\right) + p_{\boldsymbol X}\left(u_1, 100\right) \\
    &amp;= p_{\boldsymbol X}\left(100, 0\right) + p_{\boldsymbol X}\left(100, 100\right) + p_{\boldsymbol X}\left(250, 0\right) + p_{\boldsymbol X}\left(250, 100\right) \\
    &amp;= 0.20 + 0.10 + 0.05 + 0.15 = 0.50.
  \end{split}
\end{equation*}\]</span></p>
</div>
</div>
<div id="jatkuva-satunnaisvektori" class="section level3 unnumbered hasAnchor">
<h3>Jatkuva satunnaisvektori<a href="moniulotteiset-jakaumat.html#jatkuva-satunnaisvektori" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Kuten diskreetit muuttujat, myös jatkuvat muuttujat voidaan yleistää useampaan ulottuvuuteen. Jatkuvia moniulotteisia satunnaismuuttujia käsitellään samaan tapaan kuin diskreettejä mutta summat <span class="math inline">\(\left(\sum\right)\)</span> täytyy korvata integraaleilla <span class="math inline">\(\left(\int\right)\)</span>. Jatkuvien jakaumien todennäköisyysteorian rajoitamme kahteen ulottuvuuteen <span class="math inline">\(d = 2\)</span>, vaikka alla olevat määritelmät ja faktat yleistyvät suoraviivaisesti kun ulottuvuuksia on enemmän kuin kaksi <span class="math inline">\(d &gt; 2\)</span> (täytyy vain integroida useamman dimension yli).</p>
<div class="definition">
<p><span id="def:continuous" class="definition"><strong>Määritelmä 2.4  (Jatkuva satunnaisvektori) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2)^T\)</span> satunnaisvektori. Satunnaisvektori <span class="math inline">\(\boldsymbol X = (X_1, X_2)^T:S\times S\to \mathbb{R}^2\)</span> on jatkuva, jos on olemassa funktio <span class="math inline">\(f_{\boldsymbol X}:\mathbb{R}^2\to\mathbb{R}\)</span> siten, että mille tahansa tarpeeksi “kivalle”<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> joukolle <span class="math inline">\(I\subset\mathbb{R}^2\)</span>, todennäköisyys, että <span class="math inline">\(\boldsymbol X\)</span> saa arvonsa joukossa <span class="math inline">\(I\)</span> saadaan integroimalla funktiota <span class="math inline">\(f_{\boldsymbol X}\)</span> joukon <span class="math inline">\(I\)</span> yli eli
<span class="math display" id="eq:density">\[\begin{equation}
  \mathbb{P}\left(\boldsymbol X\in I\right) = \int_I  f_{\boldsymbol X}(x_1, x_2) \,\mathrm{d}\boldsymbol x
  \tag{2.4}
\end{equation}\]</span>
Tällöin funktiota <span class="math inline">\(f_{\boldsymbol X}\)</span> kutsutaan satunnaisvektorin <span class="math inline">\(\boldsymbol X\)</span> tiheysfunktioksi.</p>
</div>
<p>Esimerkiksi, jos joukko <span class="math inline">\(I\)</span> on suorakaide eli <span class="math inline">\(I = [a,b]\times[c,d]\)</span>, niin kaava <a href="moniulotteiset-jakaumat.html#eq:density">(2.4)</a> voidaan kirjoittaa muodossa
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(\boldsymbol X\in I\right)
  = \mathbb{P}\left(a\leq X_1\leq b, c\leq X_2\leq d\right)
  = \int_a^b\int_c^d  f_{\boldsymbol X}(x_1, x_2) \,\mathrm{d}x_2 \,\mathrm{d}x_1.
\end{equation*}\]</span>
Jatkuville jakaumille tiheysfunktio ajaa saman asian kuin diskreettien jakaumien pistetodennäköisyysfunktio. Tällöin luonnollisesti tiheysfunktio täyttää samantyyppiset ehdot kuin pistetodennäköisyysfunktio mutta summat täytyy korvata integraaleilla.</p>
<div class="theorem">
<p><span id="thm:unlabeled-div-12" class="theorem"><strong>Fakta 2.4  (Tiheysfunktion ominaisuudet) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2)^T\)</span> jatkuva satunnaisvektori, jolla on tiheysfunktio <span class="math inline">\(f_{\boldsymbol X}\)</span>. Tiheysfunktio toteuttaa seuraavat ehdot:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(f_{\boldsymbol X}\left(x_1, x_2\right)  \geq 0\)</span> kaikilla <span class="math inline">\((x_1, x_2)^T\in\mathbb{R}^2\)</span> (epänegatiivisuus)</p></li>
<li><p><span class="math inline">\(\int_\mathbb{R}\int_\mathbb{R} f_{\boldsymbol X}(x_1,  x_2)\,\mathrm{d}x_1 \,\mathrm{d}x_2 = 1\)</span> (integroituu ykköseen)</p></li>
</ol>
<p>Vastaavasti, jos joku mielivaltainen funktio <span class="math inline">\(g:\mathbb{R}^2\to \mathbb{R}\)</span> toteuttaa ehdot 1 ja 2, niin se on jonkin jatkuvan satunnaismuuttujan tiheysfunktio.</p>
</div>
<p>Kuten yksiulotteisten jatkuvien satunnaismuuttujien tapauksessa, myös jatkuvien satunnaisvektorien kertymäfunktio (ja jakauma) saadaan tiheysfunktion avulla.</p>
<div class="theorem">
<p><span id="thm:continuouscdf" class="theorem"><strong>Fakta 2.5  (Tiheys- ja kertymäfunktion yhteys) </strong></span>Olkoon <span class="math inline">\(\boldsymbol X = (X_1, X_2)^T\)</span> jatkuva satunnaisvektori, jolla on tiheysfunktio <span class="math inline">\(f_{\boldsymbol X}\)</span>. Tiheys- ja kertymäfunktiolla on seuraava yhteys. Kaikille <span class="math inline">\(\boldsymbol x = (x_1, x_2)\in\mathbb{R}^2\)</span> pätee
<span class="math display" id="eq:continuous-multi-cdf">\[\begin{equation}
  \begin{split}
    F_{\boldsymbol X}\left(\boldsymbol x\right)
    &amp;:= \mathbb{P}\left(X_1\leq x_1, X_2\leq x_2\right) \\
    &amp;= \int_{-\infty}^{x_1}\int_{-\infty}^{x_2}  f(x_1, x_2) \,\mathrm{d}x_2 \,\mathrm{d}x_1.
  \end{split}
  \tag{2.5}
\end{equation}\]</span></p>
</div>
<p>Kaava <a href="moniulotteiset-jakaumat.html#eq:continuous-multi-cdf">(2.5)</a> näyttää siis hyvin samankaltaiselta kuin <a href="moniulotteiset-jakaumat.html#eq:continuous-uni-cdf">(2.2)</a> – yhden integraalin sijasta on <span class="math inline">\(d = 2\)</span> integraalia.</p>
<p>Integrointi ei sisälly tälle kurssille, joten emme sisällytä yhtä paljon esimerkkejä jatkuvista satunnaisvektoreista kuin diskreeteistä. Integrointi käydään tarkemmin kurssilla <em>Mathematical tools for analytics</em>. Jatkuvien (ja diskreettien) muuttujien tapauksissa todennäköisyyksiä voidaan kuitenkin estimoida empiirisen todennäköisyyden avulla kunhan otos on tarpeeksi suuri.</p>

<div class="example">
<p><span id="exm:unlabeled-div-13" class="example"><strong>Esimerkki 2.10  (Empiirinen todennäköisyys) </strong></span>Käsittelemme esimerkin <a href="moniulotteiset-jakaumat.html#exm:body">2.1</a> havaintoaineistoa</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="moniulotteiset-jakaumat.html#cb2-1" tabindex="-1"></a>body</span></code></pre></div>
<pre><code>## # A tibble: 716 × 4
##    ShoulderWidth Belly ArmLength TotalHeight
##            &lt;int&gt; &lt;int&gt;     &lt;int&gt;       &lt;int&gt;
##  1            18    18        22          52
##  2            22    18        28          56
##  3            18    14        21          53
##  4            20    11        24          45
##  5            14    13        25          47
##  6            19    14        20          60
##  7            17    17        23          49
##  8            15    17        19          58
##  9            16    18        15          40
## 10            20    18        16          55
## # ℹ 706 more rows</code></pre>
<p>Merkitään <span class="math inline">\(X = \texttt{TotalHeight}\)</span> ja <span class="math inline">\(Y = \texttt{ArmLength}\)</span>. Havaintoaineiston avulla haluamme estimoida todennäköisyyden <span class="math inline">\(\mathbb{P}\left(X \leq 40, Y\geq 30\right)\)</span> muuttujasta <code>body</code> saatavan otoksen <span class="math inline">\((x_1, y_1), (x_2, y_2)\ldots, (x_{716}, y_{716})\)</span> avulla. Kyseessä on jonkinlainen ääritapahtuma (eng: <em>extreme event</em>), koska tarkastelemme ihmisiä, jotka ovat lyhyitä mutta heillä on pitkät kädet. Kyseisen todennäköisyyden voi estimoida empiirisellä jakaumalla eli
<span class="math display">\[\begin{equation*}
  \mathbb{P}\left(X \leq 40, Y\geq 30\right)\approx \frac{\#\overbrace{\left\{(x_i, y_i) : x_i\leq 40\ \text{ja}\ y_i\geq 30\right\}}^{=A}}{716},
\end{equation*}\]</span>
jossa notaatio <span class="math inline">\(\# A\)</span> tarkoittaa joukon <span class="math inline">\(A\)</span> alkioiden lukumäärää. Nyt kaavan oikeanpuoleinen lauseke tarvitsee vain kirjoittaa R:llä.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="moniulotteiset-jakaumat.html#cb4-1" tabindex="-1"></a>condition <span class="ot">&lt;-</span> (body<span class="sc">$</span>TotalHeight <span class="sc">&lt;=</span> <span class="dv">40</span> <span class="sc">&amp;</span> body<span class="sc">$</span>ArmLength <span class="sc">&gt;=</span> <span class="dv">30</span>)</span>
<span id="cb4-2"><a href="moniulotteiset-jakaumat.html#cb4-2" tabindex="-1"></a>p_empirical <span class="ot">&lt;-</span> <span class="fu">sum</span>(condition) <span class="sc">/</span> <span class="fu">nrow</span>(body)</span>
<span id="cb4-3"><a href="moniulotteiset-jakaumat.html#cb4-3" tabindex="-1"></a>p_empirical</span></code></pre></div>
<pre><code>## [1] 0.002793296</code></pre>
<p>Saamme siis estimoitua, että <span class="math inline">\(\mathbb{P}\left(X \leq 40, Y\geq 30\right)\approx 0.0028\)</span>. Huomaa kuitenkin, että estimaatti on epäluotettava joukon <span class="math inline">\(A\)</span> pienuuden vuoksi. Kuva <a href="moniulotteiset-jakaumat.html#fig:outlier">2.4</a> näyttää, että vain kaksi ihmistä (väritetty punaisella) sisältyy joukkoon <span class="math inline">\(A\)</span>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="moniulotteiset-jakaumat.html#cb6-1" tabindex="-1"></a><span class="fu">plot</span>(body<span class="sc">$</span>TotalHeight,</span>
<span id="cb6-2"><a href="moniulotteiset-jakaumat.html#cb6-2" tabindex="-1"></a>     body<span class="sc">$</span>ArmLength,</span>
<span id="cb6-3"><a href="moniulotteiset-jakaumat.html#cb6-3" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;skyblue&quot;</span>, <span class="st">&quot;tomato4&quot;</span>)[condition <span class="sc">+</span> <span class="dv">1</span>], <span class="co"># Point color according to condition</span></span>
<span id="cb6-4"><a href="moniulotteiset-jakaumat.html#cb6-4" tabindex="-1"></a>     <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">16</span>)[condition <span class="sc">+</span> <span class="dv">1</span>], <span class="co"># Point type according to condition</span></span>
<span id="cb6-5"><a href="moniulotteiset-jakaumat.html#cb6-5" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)[condition <span class="sc">+</span> <span class="dv">1</span>], <span class="co"># Point size according to condition</span></span>
<span id="cb6-6"><a href="moniulotteiset-jakaumat.html#cb6-6" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Height&quot;</span>,</span>
<span id="cb6-7"><a href="moniulotteiset-jakaumat.html#cb6-7" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Arm Length&quot;</span>)</span>
<span id="cb6-8"><a href="moniulotteiset-jakaumat.html#cb6-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">30</span>, <span class="at">v =</span> <span class="dv">40</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:outlier"></span>
<img src="tidaja-book_files/figure-html/outlier-1.png" alt="Hajontakuvio muuttujaa \((X, Y)^T\) vastaavasta otoksesta. Havainnot jotka sisältyvät joukkoon \(A\) ollaan merkitty suurilla punaisilla pisteillä." width="672" />
<p class="caption">
Kuva 2.4: Hajontakuvio muuttujaa <span class="math inline">\((X, Y)^T\)</span> vastaavasta otoksesta. Havainnot jotka sisältyvät joukkoon <span class="math inline">\(A\)</span> ollaan merkitty suurilla punaisilla pisteillä.
</p>
</div>
<p>Selitämme vielä hieman kuvan <a href="moniulotteiset-jakaumat.html#fig:outlier">2.4</a> tuottavan koodinpätkän logiikasta. Argumenteilla <code>col</code>, <code>pch</code> ja <code>cex</code> voidaan muokata hajontakuvion väriä, pistetyyppiä ja pisteiden kokoa. Esimerkiksi <code>pch = 4</code> vastaa rastia. Haluamme asettaa joukon <span class="math inline">\(A\)</span> alkioille oman värin <code>tomato4</code>, pistetyypin <code>16</code> ja pistekoon <code>2</code>. Vektori <code>condition</code> on <code>TRUE/FALSE</code> vektori, jossa arvo <code>TRUE</code> on asetettu vain joukon <span class="math inline">\(A\)</span> havainnoille. Huomaa myös, että R tulkitsee <code>TRUE = 1</code> ja <code>FALSE = 0</code> tehdessä operaatioita lukujen ja totuusarvojen välillä. Esimerkiksi</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="moniulotteiset-jakaumat.html#cb7-1" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">+</span> <span class="cn">FALSE</span> <span class="sc">+</span> <span class="cn">FALSE</span> <span class="sc">+</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Nyt siis <code>condition  + 1</code> on kokonaislukuvektori, jossa kaikki alkiot ovat ykkösiä paitsi joukon <span class="math inline">\(A\)</span> havaintoja vastaavat alkiot ovat kakkosia. Eli komento <code>c(4, 16)[condition + 1]</code> valitsee vektorista <span class="math inline">\((4,  16)\)</span> alkioita <span class="math inline">\(4\)</span> ja <span class="math inline">\(16\)</span> riippuen siitä, onko havainto joukossa <span class="math inline">\(A\)</span> vai ei.</p>
</div>
<p>Seuraavaksi perehdymme tarkemmin moniulotteiseen normaalijakaumaan, jonka voidaan sanoa olevan yksi tärkeimmistä moniulotteisista jakaumista.</p>
</div>
</div>
<div id="sec:normal" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Moniulotteinen normaalijakauma<a href="moniulotteiset-jakaumat.html#sec:normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="sec:cond" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Ehdolliset jakaumat ja reunajakaumat<a href="moniulotteiset-jakaumat.html#sec:cond" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="diskreetit-jakaumat" class="section level3 unnumbered hasAnchor">
<h3>Diskreetit jakaumat<a href="moniulotteiset-jakaumat.html#diskreetit-jakaumat" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="jatkuvat-jakaumat" class="section level3 unnumbered hasAnchor">
<h3>Jatkuvat jakaumat<a href="moniulotteiset-jakaumat.html#jatkuvat-jakaumat" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
</div>
<div id="sec:statistic" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Tunnusluvuista<a href="moniulotteiset-jakaumat.html#sec:statistic" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Tässä “kiva” tarkoittaa <em>mitattavaa</em> joukkoa. Tämäntyyppisten yksityiskohtien hallinta vaatii edistyneempää matematiikkaa (mittateoriaa), joka on täysin kurssin ulkopuolella.<a href="moniulotteiset-jakaumat.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-ohjelmointikielestä.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lähteet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
